### DISCUSSION TITLE
No CUDA-capable device is detected after 15 minutes of successful work

### DISCUSSION THREAD

**Discussion by maxwase** [immich-app/immich#10555] [Q&A] [answered]
### The bug

I guess I'm having the same issue, after a 10-15 minutes of photo+video uploading I get the following error for every new coming video

### The OS that Immich Server is running on

6.6.32-1-MANJARO

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.3 build.143

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
        file: hwaccel.transcoding.yml
        service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
        file: hwaccel.ml.yml
        service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
No special changes
```

### Reproduction steps

```bash
Container restart helps, but again, only for 10 minutes

I tried to go into the container and it reproduces
1. `ffmpeg -i VID.mp4 -vcodec h264_nvenc output.mp4`
2. See the error
3. Container restart
4. run `1`
5. See no error
6. Wait for 15 minutes with multiple video upload
7. run `1`
8. See the error
```

### Relevant log output

```shell
[Nest] 7  - 06/22/2024, 10:41:46 PM   ERROR [Microservices:MediaRepository] ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Selecting decoder 'hevc' because of requested hwaccel method cuda
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/library/admin/2021/06-Jun/22/VID_20210601_111439.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2021-06-01T08:15:19.000000Z
    com.android.version: 11
    com.android.capture.fps: 60.000000
  Duration: 00:00:38.74, start: 0.000000, bitrate: 15295 kb/s
  Stream #0:0[0x1](eng): Video: hevc (Main), 1 reference frame (hvc1 / 0x31637668), yuvj420p(pc, bt470bg/bt470bg/smpte170m, left), 1920x1080 (1920x1088), 15019 kb/s, SAR 1:1 DAR 16:9, 59.96 fps, 60 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2021-06-01T08:15:19.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      creation_time   : 2021-06-01T08:15:19.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
[AVHWDeviceContext @ 0x221c4030500] cu->cuInit(0) failed -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Device creation failed: -542398533.
No device available for decoder: device type cuda needed for codec hevc.
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (copy)
Device setup failed for decoder on input stream #0:0 : Generic error in an external library
[AVIOContext @ 0x221c42c0540] Statistics: 0 bytes written, 0 seeks, 0 writeouts
[AVIOContext @ 0x221c40f0180] Statistics: 148274 bytes read, 1 seeks

[Nest] 7  - 06/22/2024, 10:41:46 PM   ERROR [Microservices:MediaService] Error: ffmpeg exited with code 1: 
[Nest] 7  - 06/22/2024, 10:41:46 PM   ERROR [Microservices:MediaService] Error occurred during transcoding. Retrying with NVENC acceleration disabled.
```

**Comment by mertalev** [comment]
Try updating your GPU driver and make sure you're on the latest [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html).

**Reply by maxwase** [reply]
It seems that I already have the latest driver according to [this](https://www.nvidia.com/Download/index.aspx?lang=en-us#) page and information from NVIDIA Settings
I also have installed the toolkin earlier today, so it's up to date (1.15.0)

**Reply by TropicLegend** [reply]
I am encountering a similar issue.

```
[Nest] 19  - 07/07/2024, 3:04:14 PM     LOG [Microservices:MediaService] Started encoding video 15b9bf23-23c0-4941-afc2-e10079ba127e {"inputOptions":["-hwaccel cuda","-hwaccel_output_format cuda","-noautorotate","-threads 1"],"outputOptions":["-tune hq","-qmin 0","-rc-lookahead 20","-i_qfactor 0.75","-c:v h264_nvenc","-c:a aac","-movflags faststart","-fps_mode passthrough","-map 0:0","-map 0:1","-g 256","-v verbose","-vf scale_cuda=-2:1080:format=nv12","-preset p1","-cq:v 23"],"twoPass":false}
[Nest] 19  - 07/07/2024, 3:04:15 PM   ERROR [Microservices:MediaRepository] ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
2024-07-07T13:04:15.026451532Z   built with gcc 12 (Debian 12.2.0-14)
2024-07-07T13:04:15.026462592Z   configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
2024-07-07T13:04:15.026476512Z   libavcodec     60.  3.100 / 60.  3.100
2024-07-07T13:04:15.026488212Z   libavformat    60.  3.100 / 60.  3.100
2024-07-07T13:04:15.026494642Z   libavdevice    60.  1.100 / 60.  1.100
2024-07-07T13:04:15.026500782Z   libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Selecting decoder 'hevc' because of requested hwaccel method cuda
2024-07-07T13:04:15.026534092Z Guessed Channel Layout for Input Stream #0.1 : mono
2024-07-07T13:04:15.026540752Z Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/upload/dfd5ce2d-e0f5-4423-aedd-3884990459e9/7c/f8/7cf8b868-80ad-43dd-9bd8-32ed1a3043e4.MOV':
  Metadata:
2024-07-07T13:04:15.026552802Z     major_brand     : qt  
2024-07-07T13:04:15.026559322Z     minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2024-04-02T14:38:34.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 8.517633
2024-07-07T13:04:15.026589982Z     com.apple.quicktime.live-photo.auto: 1
    com.apple.quicktime.content.identifier: 8CF074AD-C78A-4289-80D1-ED39D18DF09A
2024-07-07T13:04:15.026622732Z     com.apple.quicktime.live-photo.vitality-score: 0.783844
    com.apple.quicktime.live-photo.vitality-scoring-version: 0
2024-07-07T13:04:15.026640732Z     com.apple.quicktime.location.ISO6709: +48.7240+009.3832+266.524/
    com.apple.quicktime.make: Apple
2024-07-07T13:04:15.026652642Z     com.apple.quicktime.model: iPhone 12 Pro
    com.apple.quicktime.software: 17.3.1
    com.apple.quicktime.creationdate: 2024-04-02T16:38:33+0200
  Duration: 00:00:02.58, start: 0.000000, bitrate: 14087 kb/s
2024-07-07T13:04:15.026676122Z   Stream #0:0[0x1](und): Video: hevc (Main), 1 reference frame (hvc1 / 0x31637668), yuvj420p(pc, smpte170m/smpte432/bt709, left), 1920x1440, 12909 kb/s, 23.37 fps, 29.92 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2024-04-02T14:38:34.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
  Stream #0:1[0x2](und): Audio: pcm_s16le (lpcm / 0x6D63706C), 44100 Hz, 1 channels, s16, 705 kb/s (default)
2024-07-07T13:04:15.026721502Z     Metadata:
      creation_time   : 2024-04-02T14:38:34.000000Z
      handler_name    : Core Media Audio
2024-07-07T13:04:15.026738622Z       vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2024-04-02T14:38:34.000000Z
2024-07-07T13:04:15.026762392Z       handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 26 kb/s (default)
    Metadata:
      creation_time   : 2024-04-02T14:38:34.000000Z
      handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 504 kb/s (default)
    Metadata:
      creation_time   : 2024-04-02T14:38:34.000000Z
2024-07-07T13:04:15.026810972Z       handler_name    : Core Media Metadata
[AVHWDeviceContext @ 0x5b73a032480] Cannot load libcuda.so.1
2024-07-07T13:04:15.026822872Z [AVHWDeviceContext @ 0x5b73a032480] Could not dynamically load CUDA
Device creation failed: -1.
2024-07-07T13:04:15.026834412Z No device available for decoder: device type cuda needed for codec hevc.
2024-07-07T13:04:15.026840112Z Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
2024-07-07T13:04:15.026851592Z   Stream #0:1 -> #0:1 (pcm_s16le (native) -> aac (native))
2024-07-07T13:04:15.026861302Z Device setup failed for decoder on input stream #0:0 : Operation not permitted
[AVIOContext @ 0x5b73a210d80] Statistics: 0 bytes written, 0 seeks, 0 writeouts
2024-07-07T13:04:15.026872982Z [AVIOContext @ 0x5b73a1902c0] Statistics: 335413 bytes read, 3 seeks
2024-07-07T13:04:15.026878682Z 
2024-07-07T13:04:15.026893962Z [Nest] 19  - 07/07/2024, 3:04:15 PM   ERROR [Microservices:MediaService] Error: ffmpeg exited with code 1: 
[Nest] 19  - 07/07/2024, 3:04:15 PM   ERROR [Microservices:MediaService] Error occurred during transcoding. Retrying with NVENC acceleration disabled.
```

**Comment by mertalev** [comment, marked as answer]
I did some more probing and it seems to be a known issue with Nvidia Container Toolkit. There are a few suggestions in [this](https://github.com/HaveAGitGat/Tdarr/issues/666) thread, but the best (without running as privileged or disabling cgroups v2) are the [official workarounds from Nvidia](https://github.com/NVIDIA/nvidia-container-toolkit/issues/48).

**Reply by TropicLegend** [reply]
Thank you very much for your reply, but unfortunately the issue with Immich persists for me even after following one of the workarounds.
Is a reboot of the GPU node needed for changes to apply or is there something else that could be the cause of this?

**Reply by TropicLegend** [reply]
Note:
I have found a workaround that works for immich.
I have executed "ldconfig" inside the container. After doing that, nvidia-smi works and FFMPEG is able to make use of the GPU.
I'll add that to the start command of the container for now as a workaround.
I do not know if this is just a specific issue in my case (probably is), but this was the workaround for me now that actually works.
If anybody knows how to actually fix this or what could be causing this, I'd appreciate any advice.
Thanks.

Cheers!

**Reply by TropicLegend** [reply]
> Note:
> 
> I have found a workaround that works for immich.
> 
> I have executed "ldconfig" inside the container. After doing that, nvidia-smi works and FFMPEG is able to make use of the GPU.
> 
> I'll add that to the start command of the container for now as a workaround.
> 
> I do not know if this is just a specific issue in my case (probably is), but this was the workaround for me now that actually works.
> 
> If anybody knows how to actually fix this or what could be causing this, I'd appreciate any advice.
> 
> Thanks.
> 
> 
> 
> Cheers!

Since the deployment was running on one of my production nodes, I was not able to reboot it until now.
After the reboot, the described issues vanished, meaning that the workaround that was initially recommended worked after the reboot.

Thanks for your support and cheers!

**Reply by mertalev** [reply]
Awesome, glad to hear it works now!

**Reply by muammar** [reply]
It means that this would work?

```
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    command: ldconfig
```

**Reply by mertalev** [reply]
I don't think it would. NVIDIA's workaround linked above is the best solution.
