### DISCUSSION TITLE
"Failed to smart search" - Internal Server Error since latest version update (upgraded to 1.135.3 from 1.134.0)

### DISCUSSION THREAD

**Discussion by tomzorz** [immich-app/immich#20081] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When I try to do a context search, I get an error back since updating the latest version - see the docker log below.

I had the machine learning features working before, but now it's broken as upgraded to 1.135.3 from 1.134.0. I wonder if there might've been something else as I haven't immediately tried a context search before updating. I haven't upgraded my unraid host or my nvidia drivers, so I don't think the issue is coming from there.

### The OS that Immich Server is running on

UnRaid 6.12.8

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

latest (but probably not relevant)

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a as I am on unraid. 

Running latest `ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.3.0` and `redis` alongside.
```

### Your .env content

```Shell
Pasting the relevant things from my unraid setup:

Machine learning host: 0.0.0.0
... Port: 3003
... Worker: 1
... Timeout: 120
NVIDIA_DRIVER_CAPABILITIES: all
device: my device ID as reported by unraid
```

### Reproduction steps

1. Try any context search, e.g. "hedgehog"
2. See immediate error, both in logs and on the UI

### Relevant log output

```shell
[Nest] 250  - 07/21/2025, 6:13:16 PM     LOG [Api:EventRepository] Websocket Connect:    QWOk2VRKqatY4yFOAAAB
[07/21/25 18:13:21] INFO     Loading textual model 'ViT-B-32__openai' to memory 
[07/21/25 18:13:21] INFO     Setting execution providers to                     
                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
2025-07-21 18:13:22.245116533 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 2 Memcpy nodes are added to the graph main_graph for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
2025-07-21 18:13:22.465823438 [E:onnxruntime:Default, cuda_call.cc:118 CudaCall] CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=62beda82f7d5 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/reduction/reduction_ops.cc ; line=571 ; expr=cudnnReduceTensor( CudaKernel::GetCudnnHandle(cuda_stream), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.Data<T>()), &zero, output_tensor, p_output); 
2025-07-21 18:13:22.465857568 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running ReduceL2 node. Name:'ReduceL2_1604' Status Message: CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=62beda82f7d5 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/reduction/reduction_ops.cc ; line=571 ; expr=cudnnReduceTensor( CudaKernel::GetCudnnHandle(cuda_stream), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.Data<T>()), &zero, output_tensor, p_output); 
[07/21/25 18:13:22] ERROR    Exception in ASGI application                      
                                                                                
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /app/immich/machine-learning/immich_ml/main.py: │
                             │ 177 in predict                                  │
                             │                                                 │
                             │   174 │   │   inputs = text                     │
                             │   175 │   else:                                 │
                             │   176 │   │   raise HTTPException(400, "Either  │
                             │ ❱ 177 │   response = await run_inference(inputs │
                             │   178 │   return ORJSONResponse(response)       │
                             │   179                                           │
                             │   180                                           │
                             │                                                 │
                             │ /app/immich/machine-learning/immich_ml/main.py: │
                             │ 200 in run_inference                            │
                             │                                                 │
                             │   197 │   │   response[entry["task"]] = output  │
                             │   198 │                                         │
                             │   199 │   without_deps, with_deps = entries     │
                             │ ❱ 200 │   await asyncio.gather(*[_run_inference │
                             │   201 │   if with_deps:                         │
                             │   202 │   │   await asyncio.gather(*[_run_infer │
                             │   203 │   if isinstance(payload, Image):        │
                             │                                                 │
                             │ /app/immich/machine-learning/immich_ml/main.py: │
                             │ 195 in _run_inference                           │
                             │                                                 │
                             │   192 │   │   │   │   message = f"Task {entry[' │
                             │       output of {dep}"                          │
                             │   193 │   │   │   │   raise HTTPException(400,  │
                             │   194 │   │   model = await load(model)         │
                             │ ❱ 195 │   │   output = await run(model.predict, │
                             │   196 │   │   outputs[model.identity] = output  │
                             │   197 │   │   response[entry["task"]] = output  │
                             │   198                                           │
                             │                                                 │
                             │ /app/immich/machine-learning/immich_ml/main.py: │
                             │ 213 in run                                      │
                             │                                                 │
                             │   210 │   if thread_pool is None:               │
                             │   211 │   │   return func(*args, **kwargs)      │
                             │   212 │   partial_func = partial(func, *args, * │
                             │ ❱ 213 │   return await asyncio.get_running_loop │
                             │   214                                           │
                             │   215                                           │
                             │   216 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ /usr/lib/python3.11/concurrent/futures/thread.p │
                             │ y:58 in run                                     │
                             │                                                 │
                             │ /app/immich/machine-learning/immich_ml/models/b │
                             │ ase.py:61 in predict                            │
                             │                                                 │
                             │    58 │   │   self.load()                       │
                             │    59 │   │   if model_kwargs:                  │
                             │    60 │   │   │   self.configure(**model_kwargs │
                             │ ❱  61 │   │   return self._predict(*inputs, **m │
                             │    62 │                                         │
                             │    63 │   @abstractmethod                       │
                             │    64 │   def _predict(self, *inputs: Any, **mo │
                             │                                                 │
                             │ /app/immich/machine-learning/immich_ml/models/c │
                             │ lip/textual.py:24 in _predict                   │
                             │                                                 │
                             │    21 │                                         │
                             │    22 │   def _predict(self, inputs: str, langu │
                             │    23 │   │   tokens = self.tokenize(inputs, la │
                             │ ❱  24 │   │   res: NDArray[np.float32] = self.s │
                             │    25 │   │   return serialize_np_array(res)    │
                             │    26 │                                         │
                             │    27 │   def _load(self) -> ModelSession:      │
                             │                                                 │
                             │ /app/immich/machine-learning/immich_ml/sessions │
                             │ /ort.py:49 in run                               │
                             │                                                 │
                             │    46 │   │   input_feed: dict[str, NDArray[np. │
                             │    47 │   │   run_options: Any = None,          │
                             │    48 │   ) -> list[NDArray[np.float32]]:       │
                             │ ❱  49 │   │   outputs: list[NDArray[np.float32] │
                             │       run_options)                              │
                             │    50 │   │   return outputs                    │
                             │    51 │                                         │
                             │    52 │   @property                             │
                             │                                                 │
                             │ /lsiopy/lib/python3.11/site-packages/onnxruntim │
                             │ e/capi/onnxruntime_inference_collection.py:220  │
                             │ in run                                          │
                             │                                                 │
                             │    217 │   │   if not output_names:             │
                             │    218 │   │   │   output_names = [output.name  │
                             │    219 │   │   try:                             │
                             │ ❱  220 │   │   │   return self._sess.run(output │
                             │    221 │   │   except C.EPFail as err:          │
                             │    222 │   │   │   if self._enable_fallback:    │
                             │    223 │   │   │   │   print(f"EP Error: {err!s │
                             ╰─────────────────────────────────────────────────╯
                             Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero     
                             status code returned while running ReduceL2 node.  
                             Name:'ReduceL2_1604' Status Message: CUDNN failure 
                             5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ;      
                             hostname=62beda82f7d5 ;                            
                             file=/onnxruntime_src/onnxruntime/core/providers/cu
                             da/reduction/reduction_ops.cc ; line=571 ;         
                             expr=cudnnReduceTensor(                            
                             CudaKernel::GetCudnnHandle(cuda_stream),           
                             reduce_desc, indices_cuda.get(), indices_bytes,    
                             workspace_cuda.get(), workspace_bytes, &one,       
                             input_tensor, reinterpret_cast<const               
                             CudaT*>(input.Data<T>()), &zero, output_tensor,    
                             p_output);                                         
[Nest] 250  - 07/21/2025, 6:13:22 PM    WARN [Api:MachineLearningRepository~u9hsyes5] Machine learning request to "http://127.0.0.1:3003" failed with status 500: Internal Server Error
[Nest] 250  - 07/21/2025, 6:13:22 PM   ERROR [Api:ErrorInterceptor~u9hsyes5] Unknown error: Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-B-32__openai","options":{"language":"en-US"}}}}' failed for all URLs
Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-B-32__openai","options":{"language":"en-US"}}}}' failed for all URLs
    at MachineLearningRepository.predict (/app/immich/server/dist/repositories/machine-learning.repository.js:98:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MachineLearningRepository.encodeText (/app/immich/server/dist/repositories/machine-learning.repository.js:121:26)
    at async SearchService.searchSmart (/app/immich/server/dist/services/search.service.js:84:25)
```

**Comment by tomzorz** [comment]
I'm in the immich discord under `tomzorz` if someone wants to poke at me directly, happy to provide whatever assistance to debug. (Linked the issue in the unraid channel as well.)

**Comment by bo0tzz** [comment]
@mertalev thoughts?

**Comment by mertalev** [comment]
It doesn't seem like an Immich issue, more likely in the driver or nvidia container toolkit. If you can't restart docker engine (not just the container), try restarting the server.

**Comment by tomzorz** [comment]
I have tried the following now:
- restarted docker engine (did not help)
- restarted the server (did not help)
- made sure I have the latest nvidia driver, reinstalled it just in case (did not help)

The issue started appearing after I upgraded to 1.135.x from 1.134.x so I continue to believe the issue might be on the immich side. Nothing else has changed on my server / environment (on purpose, as I try update late to avoid breaking things).

**Comment by tomzorz** [comment]
One more log entry from just now, although mostly seems to be the same

```
[Nest] 865  - 07/22/2025, 10:39:36 AM     LOG [Api:EventRepository] Websocket Connect:    c_cfCLhz6SvwRArBAAAD
[07/22/25 10:39:40] INFO     Loading textual model 'ViT-B-32__openai' to memory 
[07/22/25 10:39:40] INFO     Setting execution providers to                     
                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
2025-07-22 10:39:40.658508526 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 2 Memcpy nodes are added to the graph main_graph for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
2025-07-22 10:39:40.787998154 [E:onnxruntime:Default, cuda_call.cc:118 CudaCall] CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=62beda82f7d5 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/reduction/reduction_ops.cc ; line=571 ; expr=cudnnReduceTensor( CudaKernel::GetCudnnHandle(cuda_stream), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.Data<T>()), &zero, output_tensor, p_output); 
2025-07-22 10:39:40.788028684 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running ReduceL2 node. Name:'ReduceL2_1604' Status Message: CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=62beda82f7d5 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/reduction/reduction_ops.cc ; line=571 ; expr=cudnnReduceTensor( CudaKernel::GetCudnnHandle(cuda_stream), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.Data<T>()), &zero, output_tensor, p_output); 
[07/22/25 10:39:40] ERROR    Exception in ASGI application                      
                                                                                
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /app/immich/machine-learning/immich_ml/main.py: │
                             │ 177 in predict                                  │
                             │                                                 │
                             │   174 │   │   inputs = text                     │
                             │   175 │   else:                                 │
                             │   176 │   │   raise HTTPException(400, "Either  │
                             │ ❱ 177 │   response = await run_inference(inputs │
                             │   178 │   return ORJSONResponse(response)       │
                             │   179                                           │
                             │   180                                           │
                             │                                                 │
                             │ /app/immich/machine-learning/immich_ml/main.py: │
                             │ 200 in run_inference                            │
                             │                                                 │
                             │   197 │   │   response[entry["task"]] = output  │
                             │   198 │                                         │
                             │   199 │   without_deps, with_deps = entries     │
                             │ ❱ 200 │   await asyncio.gather(*[_run_inference │
                             │   201 │   if with_deps:                         │
                             │   202 │   │   await asyncio.gather(*[_run_infer │
                             │   203 │   if isinstance(payload, Image):        │
                             │                                                 │
                             │ /app/immich/machine-learning/immich_ml/main.py: │
                             │ 195 in _run_inference                           │
                             │                                                 │
                             │   192 │   │   │   │   message = f"Task {entry[' │
                             │       output of {dep}"                          │
                             │   193 │   │   │   │   raise HTTPException(400,  │
                             │   194 │   │   model = await load(model)         │
                             │ ❱ 195 │   │   output = await run(model.predict, │
                             │   196 │   │   outputs[model.identity] = output  │
                             │   197 │   │   response[entry["task"]] = output  │
                             │   198                                           │
                             │                                                 │
                             │ /app/immich/machine-learning/immich_ml/main.py: │
                             │ 213 in run                                      │
                             │                                                 │
                             │   210 │   if thread_pool is None:               │
                             │   211 │   │   return func(*args, **kwargs)      │
                             │   212 │   partial_func = partial(func, *args, * │
                             │ ❱ 213 │   return await asyncio.get_running_loop │
                             │   214                                           │
                             │   215                                           │
                             │   216 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ /usr/lib/python3.11/concurrent/futures/thread.p │
                             │ y:58 in run                                     │
                             │                                                 │
                             │ /app/immich/machine-learning/immich_ml/models/b │
                             │ ase.py:61 in predict                            │
                             │                                                 │
                             │    58 │   │   self.load()                       │
                             │    59 │   │   if model_kwargs:                  │
                             │    60 │   │   │   self.configure(**model_kwargs │
                             │ ❱  61 │   │   return self._predict(*inputs, **m │
                             │    62 │                                         │
                             │    63 │   @abstractmethod                       │
                             │    64 │   def _predict(self, *inputs: Any, **mo │
[Nest] 865  - 07/22/2025, 10:39:40 AM   ERROR [Api:ErrorInterceptor~qpf7pppv] Unknown error: Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-B-32__openai","options":{"language":"en-US"}}}}' failed for all URLs
                             │                                                 │
Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-B-32__openai","options":{"language":"en-US"}}}}' failed for all URLs
                             │ /app/immich/machine-learning/immich_ml/models/c │    at MachineLearningRepository.predict (/app/immich/server/dist/repositories/machine-learning.repository.js:98:15)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MachineLearningRepository.encodeText (/app/immich/server/dist/repositories/machine-learning.repository.js:121:26)
                             │ lip/textual.py:24 in _predict                   │    at async SearchService.searchSmart (/app/immich/server/dist/services/search.service.js:84:25)

                             │                                                 │
                             │    21 │                                         │
                             │    22 │   def _predict(self, inputs: str, langu │
                             │    23 │   │   tokens = self.tokenize(inputs, la │
                             │ ❱  24 │   │   res: NDArray[np.float32] = self.s │
                             │    25 │   │   return serialize_np_array(res)    │
                             │    26 │                                         │
                             │    27 │   def _load(self) -> ModelSession:      │
                             │                                                 │
                             │ /app/immich/machine-learning/immich_ml/sessions │
                             │ /ort.py:49 in run                               │
                             │                                                 │
                             │    46 │   │   input_feed: dict[str, NDArray[np. │
                             │    47 │   │   run_options: Any = None,          │
                             │    48 │   ) -> list[NDArray[np.float32]]:       │
                             │ ❱  49 │   │   outputs: list[NDArray[np.float32] │
                             │       run_options)                              │
                             │    50 │   │   return outputs                    │
                             │    51 │                                         │
                             │    52 │   @property                             │
                             │                                                 │
                             │ /lsiopy/lib/python3.11/site-packages/onnxruntim │
                             │ e/capi/onnxruntime_inference_collection.py:220  │
                             │ in run                                          │
                             │                                                 │
                             │    217 │   │   if not output_names:             │
                             │    218 │   │   │   output_names = [output.name  │
                             │    219 │   │   try:                             │
                             │ ❱  220 │   │   │   return self._sess.run(output │
                             │    221 │   │   except C.EPFail as err:          │
                             │    222 │   │   │   if self._enable_fallback:    │
                             │    223 │   │   │   │   print(f"EP Error: {err!s │
                             ╰─────────────────────────────────────────────────╯
                             Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero     
                             status code returned while running ReduceL2 node.  
                             Name:'ReduceL2_1604' Status Message: CUDNN failure 
                             5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ;      
                             hostname=62beda82f7d5 ;                            
                             file=/onnxruntime_src/onnxruntime/core/providers/cu
                             da/reduction/reduction_ops.cc ; line=571 ;         
                             expr=cudnnReduceTensor(                            
                             CudaKernel::GetCudnnHandle(cuda_stream),           
                             reduce_desc, indices_cuda.get(), indices_bytes,    
                             workspace_cuda.get(), workspace_bytes, &one,       
                             input_tensor, reinterpret_cast<const               
                             CudaT*>(input.Data<T>()), &zero, output_tensor,    
                             p_output);                                         
[Nest] 865  - 07/22/2025, 10:39:40 AM    WARN [Api:MachineLearningRepository~qpf7pppv] Machine learning request to "http://127.0.0.1:3003" failed with status 500: Internal Server Error
```

**Comment by mertalev** [comment]
> I have tried the following now:
> 
> - restarted docker engine (did not help)
> 
> - restarted the server (did not help)
> 
> - made sure I have the latest nvidia driver, reinstalled it just in case (did not help)
> 
> 
> 
> The issue started appearing after I upgraded to 1.135.x from 1.134.x so I continue to believe the issue might be on the immich side. Nothing else has changed on my server / environment (on purpose, as I try update late to avoid breaking things).

Hmm, maybe it's a regression in ONNX Runtime then? Does the issue persist if you downgrade to 1.134.0?

**Comment by tomzorz** [comment]
@mertalev I haven't attempted that yet as I wasn't sure that's a supported thing (e.g. db migrations?) But I'll try that then

**Comment by trekimann** [comment]
I am having the same issue on 2 servers, both on unraid like you and both with Quadros. I have tried rolling to old Nvidia drivers, restarting machines, changing the clip models, changing PCIe slots. If rolling to an older Immich fixes it please post your success.

**Comment by tomzorz** [comment]
Welp I downgraded to `cuda-v1.134.0-ig103` (I think that's the last 1.134.x image before the latest 1.135.x) but now the image seems to be stuck in a boot loop due to invalid db migrations:

```
[Nest] 845  - 07/22/2025, 4:53:22 PM     LOG [Api:DatabaseRepository] targetLists=256, current=256 for clip_index of 134565 rows
[Nest] 845  - 07/22/2025, 4:53:22 PM     LOG [Api:DatabaseRepository] targetLists=256, current=256 for face_index of 158343 rows
[Nest] 845  - 07/22/2025, 4:53:22 PM     LOG [Api:DatabaseRepository] Running migrations, this may take a while
[Nest] 845  - 07/22/2025, 4:53:22 PM   ERROR [Api:DatabaseRepository] Kysely migrations failed: Error: corrupted migrations: previously executed migration 1749067526135-UserOnboardingDefault is missing
Error: corrupted migrations: previously executed migration 1749067526135-UserOnboardingDefault is missing
    at #ensureNoMissingMigrations (/app/immich/server/node_modules/kysely/dist/cjs/migration/migrator.js:487:23)
    at #getState (/app/immich/server/node_modules/kysely/dist/cjs/migration/migrator.js:439:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async run (/app/immich/server/node_modules/kysely/dist/cjs/migration/migrator.js:409:31)
    at async /app/immich/server/node_modules/kysely/dist/cjs/kysely.js:569:32
    at async DefaultConnectionProvider.provideConnection (/app/immich/server/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
    at async #migrate (/app/immich/server/node_modules/kysely/dist/cjs/migration/migrator.js:268:20)
    at async DatabaseRepository.runMigrations (/app/immich/server/dist/repositories/database.repository.js:356:36)
    at async /app/immich/server/dist/services/database.service.js:105:17
    at async /app/immich/server/dist/repositories/database.repository.js:377:27
api worker exited with code 1
```

This log block keeps being repeated every few seconds, seems like the boot process tries to re-run it until it works. If anyone knows how to fix that without yeeting my db into the sun, let me know (I don't think I have any backups from 1.134.0, my only backups are wayyy older sadly)

**Comment by tomzorz** [comment]
Restored to latest `cuda` image, thankfully DB seems to be okay (although I am getting the same error `CUDNN_STATUS_EXECUTION_FAILED`)

**Comment by tomzorz** [comment]
Spent some time spelunking in the changes in between the versions, and there were 4 commits talking about updating machine learning dependencies, so that might be where the issue is coming from https://github.com/immich-app/immich/compare/v1.134.0...v1.135.0

**Comment by LokiLuciferase** [comment]
In case anyone comes here from Google as well, I just had the same issue not with Unraid but with a current https://github.com/imagegenius/docker-immich `cuda` container, running on Debian 12.

I was able to fix it temporarily by simply deploying a `immich-machine-learning:v1.135.3-cuda` container to the same host and pointing the immich web service to it for all ML tasks. So it is probably not an issue with the host NVIDIA infrastructure. My guess is incompatible CUDA or ONNX libraries built into the `docker-immich` container. No idea how that relates to the issue under Unraid specifically, but hopefully it's a useful pointer.

**Reply by trekimann** [reply]
Have you got a docker file or docker compose to hand for just the machine learning container?

**Reply by LokiLuciferase** [reply]
Here's the relevant parts of my docker compose file :

```
  # this is a temporary fallback due to: https://github.com/immich-app/immich/discussions/20081
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.135.3-cuda
    container_name: immich-machine-learning
    volumes:
      - "/my/cache/dir/immich/immich-ml:/cache"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
```
At least for me, that works without a hitch after adding http://immich-machine-learning:3003 to the web interface's machine learning servers - just make sure they're in the same docker network.

**Comment by bo0tzz** [comment]
I now count 3 reports of this issue and they're all on the imagegenius AIO image, so you might want to report this on their github.

**Reply by WildBrianNL** [reply]
https://github.com/imagegenius/docker-immich/issues/591

**Comment by tomzorz** [comment]
The new image update has fixed the issue https://github.com/imagegenius/docker-immich/pull/595

**Comment by DrSpaldo** [comment]
I just wanted to jump on and post in case someone like me comes across this exact issue and is NOT using imagegenius version on Unraid, but using the docker stack method. I just started having this issue after the 2.x releases (I think - it was working in the last 2-3 weeks but stopped).  Then I found this release - https://github.com/immich-app/immich/releases/tag/v1.133.0

Worked out that there had been changes I must have missed to the postgres DB -  _image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0_  Then read the [docs ](https://docs.immich.app/install/docker-compose)and noticed it had again been updated, now to _ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23_

So, updated the docker compose on Unraid. Immich loaded, smart search still broken and throwing the same errors... 

Tried rebooting the unraid machine, tried 5 different ML CLIP models, re-indexed smart search every time. No change, same errors. 

I am now testing on another machine, also unraid but running a 3060 instead of my 1070 on the original machine. Currently doing the re-index and will advise if the cause was the older graphics card. I cannot find any reference in the docs/release notes that the old card isn't supported though, it only said it needs CUDA (NVIDIA GPUs with [compute capability](https://developer.nvidia.com/cuda-gpus) 5.2 or higher). The only real difference between the 1070 nvidia-smi is that it says CUDA 13 and the 3060 says CUDA 12.8 .... I am not sure if that plays a factor in it, or if the card isn't supported anymore... This may be worthy of another issue, if so, please split it away. It is just the errors are so similar.

Here is my log regardless

```
2025-10-18 00:50:46.409629386 [E:onnxruntime:Default, cuda_call.cc:118 CudaCall] CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=4504f82d37f2 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/reduction/reduction_ops.cc ; line=571 ; expr=cudnnReduceTensor( CudaKernel::GetCudnnHandle(cuda_stream), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.Data<T>()), &zero, output_tensor, p_output); 
2025-10-18 00:50:46.409675506 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running ReduceL2 node. Name:'/ReduceL2' Status Message: CUDNN failure 5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=4504f82d37f2 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/reduction/reduction_ops.cc ; line=571 ; expr=cudnnReduceTensor( CudaKernel::GetCudnnHandle(cuda_stream), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.Data<T>()), &zero, output_tensor, p_output); 
[10/18/25 00:50:46] ERROR    Exception in ASGI application                      
                                                                                
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/immich_ml/main.py:177 in predict       │
                             │                                                 │
                             │   174 │   │   inputs = text                     │
                             │   175 │   else:                                 │
                             │   176 │   │   raise HTTPException(400, "Either  │
                             │ ❱ 177 │   response = await run_inference(inputs │
                             │   178 │   return ORJSONResponse(response)       │
                             │   179                                           │
                             │   180                                           │
                             │                                                 │
                             │ /usr/src/immich_ml/main.py:200 in run_inference │
                             │                                                 │
                             │   197 │   │   response[entry["task"]] = output  │
                             │   198 │                                         │
                             │   199 │   without_deps, with_deps = entries     │
                             │ ❱ 200 │   await asyncio.gather(*[_run_inference │
                             │   201 │   if with_deps:                         │
                             │   202 │   │   await asyncio.gather(*[_run_infer │
                             │   203 │   if isinstance(payload, Image):        │
                             │                                                 │
                             │ /usr/src/immich_ml/main.py:195 in               │
                             │ _run_inference                                  │
                             │                                                 │
                             │   192 │   │   │   │   message = f"Task {entry[' │
                             │       output of {dep}"                          │
                             │   193 │   │   │   │   raise HTTPException(400,  │
                             │   194 │   │   model = await load(model)         │
                             │ ❱ 195 │   │   output = await run(model.predict, │
                             │   196 │   │   outputs[model.identity] = output  │
                             │   197 │   │   response[entry["task"]] = output  │
                             │   198                                           │
                             │                                                 │
                             │ /usr/src/immich_ml/main.py:213 in run           │
                             │                                                 │
                             │   210 │   if thread_pool is None:               │
                             │   211 │   │   return func(*args, **kwargs)      │
                             │   212 │   partial_func = partial(func, *args, * │
                             │ ❱ 213 │   return await asyncio.get_running_loop │
                             │   214                                           │
                             │   215                                           │
                             │   216 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ /usr/local/lib/python3.11/concurrent/futures/th │
                             │ read.py:58 in run                               │
                             │                                                 │
                             │ /usr/src/immich_ml/models/base.py:61 in predict │
                             │                                                 │
                             │    58 │   │   self.load()                       │
                             │    59 │   │   if model_kwargs:                  │
                             │    60 │   │   │   self.configure(**model_kwargs │
                             │ ❱  61 │   │   return self._predict(*inputs, **m │
                             │    62 │                                         │
                             │    63 │   @abstractmethod                       │
                             │    64 │   def _predict(self, *inputs: Any, **mo │
                             │                                                 │
                             │ /usr/src/immich_ml/models/clip/textual.py:24 in │
                             │ _predict                                        │
                             │                                                 │
                             │    21 │                                         │
                             │    22 │   def _predict(self, inputs: str, langu │
                             │    23 │   │   tokens = self.tokenize(inputs, la │
                             │ ❱  24 │   │   res: NDArray[np.float32] = self.s │
                             │    25 │   │   return serialize_np_array(res)    │
                             │    26 │                                         │
                             │    27 │   def _load(self) -> ModelSession:      │
                             │                                                 │
                             │ /usr/src/immich_ml/sessions/ort.py:49 in run    │
                             │                                                 │
                             │    46 │   │   input_feed: dict[str, NDArray[np. │
                             │    47 │   │   run_options: Any = None,          │
                             │    48 │   ) -> list[NDArray[np.float32]]:       │
                             │ ❱  49 │   │   outputs: list[NDArray[np.float32] │
                             │       run_options)                              │
                             │    50 │   │   return outputs                    │
                             │    51 │                                         │
                             │    52 │   @property                             │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:22 │
                             │ 0 in run                                        │
                             │                                                 │
                             │    217 │   │   if not output_names:             │
                             │    218 │   │   │   output_names = [output.name  │
                             │    219 │   │   try:                             │
                             │ ❱  220 │   │   │   return self._sess.run(output │
                             │    221 │   │   except C.EPFail as err:          │
                             │    222 │   │   │   if self._enable_fallback:    │
                             │    223 │   │   │   │   print(f"EP Error: {err!s │
                             ╰─────────────────────────────────────────────────╯
                             Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero     
                             status code returned while running ReduceL2 node.  
                             Name:'/ReduceL2' Status Message: CUDNN failure     
                             5000: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ;      
                             hostname=4504f82d37f2 ;                            
                             file=/onnxruntime_src/onnxruntime/core/providers/cu
                             da/reduction/reduction_ops.cc ; line=571 ;         
                             expr=cudnnReduceTensor(                            
                             CudaKernel::GetCudnnHandle(cuda_stream),           
                             reduce_desc, indices_cuda.get(), indices_bytes,    
                             workspace_cuda.get(), workspace_bytes, &one,       
                             input_tensor, reinterpret_cast<const               
                             CudaT*>(input.Data<T>()), &zero, output_tensor,    
                             p_output);                
```

**Reply by DrSpaldo** [reply]
I searched using another term and found this - https://github.com/immich-app/immich/issues/22982

Maybe it just relates to that?
