### DISCUSSION TITLE
Hardware transcode issues

### DISCUSSION THREAD

**Discussion by thfsilvab** [immich-app/immich#23133] [Q&A]
Hello! I'm trying to use hardware transcode with an NVIDIA GPU, I know this has the potential to be again NVIDIA not being cool with Linux but I reached no results with my debug. Apparently FFMPEG is unable to find `libcuda.so.1`.

<details>

<summary>Error Log</summary>

```sh
[Nest] 2  - 10/21/2025, 2:57:58 PM   ERROR [Microservices:MediaRepository] ffmpeg version 7.1.1-Jellyfin Copyright (c) 2000-2025 the FFmpeg developers
  built with gcc 14 (Debian 14.2.0-19)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.101 / 61. 19.101
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Selecting decoder 'hevc' because of requested hwaccel method cuda
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/upload/24e426f4-727c-4db3-b48e-db7904caa383/ec/c7/ecc7b4a5-9429-4785-92e0-65a2f13c1549.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2025-08-09T21:31:37.000000Z
    com.android.version: 15
    com.android.capture.fps: 60.000000
    com.samsung.android.utc_offset: -0300
  Duration: 00:01:20.70, start: 0.000000, bitrate: 144249 kb/s
  Stream #0:0[0x1](eng): Video: hevc (Main 10), 1 reference frame (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/smpte2084, left), 3840x2160, 143987 kb/s, 59.30 fps, 59 tbr, 90k tbn (default)
      Metadata:
        creation_time   : 2025-08-09T21:31:37.000000Z
        handler_name    : VideoHandle
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
      Metadata:
        creation_time   : 2025-08-09T21:31:37.000000Z
        handler_name    : SoundHandle
        vendor_id       : [0][0][0][0]
[out#0/mp4 @ 0x55f0b15778c0] Adding streams from explicit maps...
[vost#0:0/h264_nvenc @ 0x55f0b15aa7c0] Created video stream from input stream 0:0
[AVHWDeviceContext @ 0x55f0b15ac9c0] Cannot load libcuda.so.1
[AVHWDeviceContext @ 0x55f0b15ac9c0] Could not dynamically load CUDA
Device creation failed: -1.
[vist#0:0/hevc @ 0x55f0b15675c0] [dec:hevc @ 0x55f0b1575940] No device available for decoder: device type cuda needed for codec hevc.
[vist#0:0/hevc @ 0x55f0b15675c0] [dec:hevc @ 0x55f0b1575940] Hardware device setup failed for decoder: Operation not permitted
Error opening output file /data/encoded-video/24e426f4-727c-4db3-b48e-db7904caa383/97/dd/97dda425-77cf-4fba-985f-f0952518070c.mp4.
Error opening output files: Operation not permitted
[AVIOContext @ 0x55f0b1569380] Statistics: 5360182 bytes read, 2 seeks
```

</details>

<details>

<summary>Compose Service</summary>

```yaml
  server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - server_uploads:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283/tcp
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2gb
        reservations:
          devices:
            - capabilities: ["gpu", "compute", "video"]
              count: all
              driver: nvidia
```

</details>

Podman is making the GPU available for containers (all packages are installed, like `nvidia-container-toolkit` and `nvidia-utils`), I tested it as in their documentation https://podman-desktop.io/docs/podman/gpu and by also running Ollama with my GPU. I also tried giving the container the specific device ID to use but with no success.

Am I missing any CUDA specific configuration to make this work?
I appreciate the help!

**Comment by kitch-jared** [comment]
I'm running into this issue as well. At least, I assume it is the same issue. I have moved my server over to podman, and I, too, am unable to get it to use the gpu. I know that there are differences with how podman and docker handles connecting the devices, but I made those changes without resolution. (anecdotally, changing over to the devices options in plex allowed transcoding to work properly there)

It sounds like @thfsilvab has gone further than my limited skills have allowed, but I have verified that the gpu is seen inside the container. It just doesn't seem to be using it (as seen on nvidia-smi).

**Comment by vorezal** [comment]
I don't know if this will help either or both of you, but try setting the following environment variables on the container:
```
NVIDIA_DRIVER_CAPABILITIES=all
NVIDIA_VISIBLE_DEVICES=all
```
The second _shouldn't_ be necessary, especially if the container sees the gpu, but the first might be required to enable video encoding capabilities. I'm fairly sure adding those capabilities to the devices->capabilities section of docker compose does not work as intended. Docker documentation [here](https://docs.docker.com/reference/compose-file/deploy/#capabilities) states that the options are "gpu" and "tpu" without any mention of the others, though I have no idea if they were supported that way in the past.

Edit: Sorry, scratch the environment variable suggestion. They are already built into the Immich server image.

**Comment by zeyadtamimi** [comment]
Hey Folks,

I ran into this as well with both immich and plex. There is a similar issue raised on the linuxserver plex image https://github.com/linuxserver/docker-plex/issues/403

While I have not tired the same fix here I think this is an issue with the use of `LD_LIBRARY_PATH` in the immich server image which is set to `/usr/lib/jellyfin-ffmpeg/lib:/usr/lib/wsl/lib`. The NVIDIA container utilities hook will install `libcuda` ( among other libraries ) in  `/usr/lib`.

I believe overriding the `LD_LIBRARY_PATH` env variable to be `/usr/lib/jellyfin-ffmpeg/lib:/usr/lib/wsl/lib:/usr/lib:/lib` in the `podman run` command for the server should do the trick as this is what worked for me with the official plex image.

Disclaimer: I have not tried this with immich yet so YMMV
