### DISCUSSION TITLE
ML on Intel n100

### DISCUSSION THREAD

**Discussion by serj-47** [immich-app/immich#25116] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

not work hw.accel ML

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

2.4.1

### Version of Immich Mobile App

2.4.1

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://docs.immich.app/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
     file: hwaccel.ml.yml
     service: openvino # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
default
```

### Reproduction steps

I deployed the containers on my server and started the task of defining the text on the photo. I run intel_gpu_top and it shows the gpu is not being used in any way.

hwaccel.ml.yml - default

```
docker logs immich_machine_learning
[01/07/26 18:20:51] INFO     Starting gunicorn 23.0.0
[01/07/26 18:20:51] INFO     Listening at: http://[::]:3003 (11)
[01/07/26 18:20:51] INFO     Using worker: immich_ml.config.CustomUvicornWorker
[01/07/26 18:20:51] INFO     Booting worker with pid: 15
[01/07/26 18:20:53] INFO     Started server process [15]
[01/07/26 18:20:53] INFO     Waiting for application startup.
[01/07/26 18:20:53] INFO     Created in-memory cache with unloading after 300s
                             of inactivity.
[01/07/26 18:20:53] INFO     Initialized request thread pool with 4 threads.
[01/07/26 18:20:53] INFO     Application startup complete.
[01/07/26 18:32:21] INFO     Loading detection model 'PP-OCRv5_mobile' to memory
[01/07/26 18:32:21] INFO     Setting execution providers to
                             ['OpenVINOExecutionProvider',
                             'CPUExecutionProvider'], in descending order of
                             preference
[01/07/26 18:32:21] INFO     Loading recognition model 'PP-OCRv5_mobile' to
                             memory
[01/07/26 18:32:21] INFO     Setting execution providers to
                             ['OpenVINOExecutionProvider',
                             'CPUExecutionProvider'], in descending order of
                             preference
[INFO] 2026-01-07 18:32:22,069 [RapidOCR] base.py:22: Using engine_name: onnxruntime
```

```
docker exec -t immich_machine_learning ls -la /dev/dri
total 0
drwxr-xr-x 2 root root        80 Jan  7 18:20 .
drwxr-xr-x 7 root root       380 Jan  7 18:20 ..
crw-rw---- 1 root video 226,   0 Jan  7 18:20 card0
crw-rw---- 1 root   105 226, 128 Jan  7 18:20 renderD128
```

### Relevant log output

```shell

```

**Comment by serj-47** [comment]
Guys, well, has no one raised hw accel machine learning on intel n100? I have updated all packages on debian, the kernel to 6.1.0-42. The video driver is installed from apt, there may be a problem with it, it's not very old, though, or maybe for hw machine learning to work, I also need to enable hardware transcoding, but I'm not sure.

```
apt show intel-media-va-driver
Package: intel-media-va-driver
Version: 23.1.1+dfsg1-1
Priority: optional
Section: video
Source: intel-media-driver
Maintainer: Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>
Installed-Size: 14,5 MB
Provides: va-driver
Depends: libva-driver-abi-1.17, libc6 (>= 2.34), libgcc-s1 (>= 3.0), libigdgmm12 (>= 22.3.3+ds1), libstdc++6 (>= 11)
```

**Comment by serj-47** [comment, marked as answer]
The problem was that I deployed the containers first and then edited docker-compose, and for some reason all time the machine_learning container was used by default instead of the machine_learning-openvino container.
