### DISCUSSION TITLE
Falling back to ['CPUExecutionProvider'] and retrying.

### DISCUSSION THREAD

**Discussion by trex2000** [immich-app/immich#26455] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I am running Immich inside container under Ubuntu OS, with NVIDIA RTX A1000 GPU. I run ollama, whisper, piper and plex transcoder services on the GPU as well. All are working fine except Immich Machine learning:

After a while Immich fails to see  the GPU and only restarting docker (not just the container) seems to solve the issue. 
I don't think it's a docker issue as all other services what are using the GPU continue to work.

 `Falling back to ['CPUExecutionProvider'] and retrying.

****************************************

[02/22/26 18:27:57] INFO     Loading textual model 'ViT-B-32__openai' to memory 

[02/22/26 18:27:57] INFO     Setting execution providers to                     

                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 

                             in descending order of preference                  

2026-02-22 18:28:04.810957213 [E:onnxruntime:Default, cuda_call.cc:123 CudaCall] CUDA failure 100: no CUDA-capable device is detected ; GPU=-1 ; hostname=17cd13b978f7 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc ; line=67 ; expr=cudaGetDeviceCount(&num_devices); 

*************** EP Error ***************

EP Error /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc:60 static onnxruntime::CUDAExecutionProviderInfo onnxruntime::CUDAExecutionProviderInfo::FromProviderOptions(const onnxruntime::ProviderOptions&) [ONNXRuntimeError] : 1 : FAIL : provider_options_utils.h:187 Parse Failed to parse provider option "device_id": CUDA failure 100: no CUDA-capable device is detected ; GPU=-1 ; hostname=17cd13b978f7 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc ; line=67 ; expr=cudaGetDeviceCount(&num_devices); 

 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']

Falling back to ['CPUExecutionProvider'] and retrying.

****************************************`

### The OS that Immich Server is running on

Ubuntu 24.10 LTS

### Version of Immich Server

v2.5.6

### Version of Immich Mobile App

v2.5.6

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Device make and model

HP Microserver Gen 8

### Your docker-compose.yml content

```YAML
root@barney:~# cat /var/bin/Updater/updateScripts/immich/docker-compose.yml
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
       file: hwaccel.transcoding.yml
       service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/data
      - ${IMPORT_LOCATION}:/import
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
       file: hwaccel.ml.yml
       service: cuda # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    environment:
      LD_LIBRARY_PATH: /usr/local/cuda:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

#  database:
#    container_name: immich_postgres
#    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:c44be5f2871c59362966d71eab4268170eb6f5653c0e6170184e72b38ffdf107
#    environment:
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_DB: ${DB_DATABASE_NAME}
#      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
#    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
#      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
#    shm_size: 128mb
#    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
root@barney:~# cat /var/bin/Updater/updateScripts/immich/.env
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/500gb/Immich/

# The location where Older pictures are stored that will be imported
IMPORT_LOCATION=/mnt/500gb/Pictures/


# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=/var/lib/postgresql/data

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Bucharest

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release


# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=ladyhawke

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=immich
DB_HOSTNAME=192.168.1.3
DB_PASSWORD=pass
DB_DATABASE_NAME=immich
DB_URL='postgresql://immich:pass@192.168.1.3:5432/immich'


#fine tune HW accelaration
MACHINE_LEARNING_REQUEST_THREADS=1
MACHINE_LEARNING_WORKERS=1
MACHINE_LEARNING_MODEL_TTL=0
NVIDIA_VISIBLE_DEVICES=all

root@barney:~#
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```

**Comment by shadowlocked** [comment]
I solved this, with a great deal of messing about with ChatGPT, by downgrading my NVIDIA driver to one below the level the associated ONNX file was compiled at. So that was 546.33-desktop-win10-win11-64bit-international-dch-whql.exe (546.3+), which I had to hunt round for. Eventually I got it working, but there is an Immich bug that closes down CUDA after a while under heavy load, so I use a Powershell script to monitor GPU load and restart immich ML remote container on the 3090 GPU on my LAN if GPU load falls down to a point where it is clear that CUDA is no longer processing immich material.

docker-compose.yml

`name: immich_remote_ml

services:
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      file: hwaccel.ml.yml
      service: cuda
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - ORT_DISABLE_CUDA_GRAPH=1
    volumes:
      - model-cache:/cache
    restart: always
    ports:
      - 3003:3003

volumes:
  model-cache:`

hwaccel.ml.yml (same directory)


`services:
  cuda:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]`

**Reply by trex2000** [reply]
hmm, thanks for letting me know. I am running under Linux where i have also set persistent mode, so the kernel should not unload the module. And I am running all other GPU dependent docker containers just fine.

**Reply by trex2000** [reply]
https://dev.to/deskpai/the-hidden-pitfalls-of-onnxruntime-gpu-setup-4kb7

this might be interesting to investigate

**Comment by shadowlocked** [comment]
I should add that my above-mentioned method no longer works, and I have no idea why. Getting a local GPU operational and staying operational for Immich over the LAN is absolute murder, and I wish this ONNX approach could be rethought in favor of something less fragile, even if it is less discrete.
