### DISCUSSION TITLE
Machine Learning CUDA error cudaErrorNoKernelImageForDevice

### DISCUSSION THREAD

**Discussion by 10Andrea10** [immich-app/immich#8099] [Q&A]
### The bug

# Specs
- Ubuntu 22.04.4 LTS running bare metal locally
- NVRM version: NVIDIA UNIX x86_64 Kernel Module  535.161.07  Sat Feb 17 22:55:48 UTC 2024
- Docker version 25.0.5, build 5dc9bcc
- NVIDIA Corporation GM108M [GeForce 920MX] (rev a2)
- Driver Version: 535.161.07
- CUDA Version: 12.2

# Steps
1. Install Nvidia drivers: https://ubuntu.com/server/docs/nvidia-drivers-installation
2. Install Nvidia Toolkit: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
3. Test [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/sample-workload.html) passes
4. Install Immich: https://immich.app/docs/install/docker-compose
5. Edit docker-compose: https://immich.app/docs/features/ml-hardware-acceleration
6. Upload from mobile app some photos and videos
7. Tried others ML models

# Result
- No faces and ML tasks have been actually completed
- No errors in the Job page

Machine-learning container log (there's one for each image processed)
```
[03/20/24 10:49:48] ERROR    Exception in ASGI application                      
                                                                                
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/app/main.py:118 in predict             │
                             │                                                 │
                             │   115 │                                         │
                             │   116 │   model = await load(await model_cache. │
                             │       ttl=settings.model_ttl, **kwargs))        │
                             │   117 │   model.configure(**kwargs)             │
                             │ ❱ 118 │   outputs = await run(model.predict, in │
                             │   119 │   return ORJSONResponse(outputs)        │
                             │   120                                           │
                             │   121                                           │
                             │                                                 │
                             │ /usr/src/app/main.py:125 in run                 │
                             │                                                 │
                             │   122 async def run(func: Callable[..., Any], i │
                             │   123 │   if thread_pool is None:               │
                             │   124 │   │   return func(inputs)               │
                             │ ❱ 125 │   return await asyncio.get_running_loop │
                             │   126                                           │
                             │   127                                           │
                             │   128 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ /usr/local/lib/python3.11/concurrent/futures/th │
                             │ read.py:58 in run                               │
                             │                                                 │
                             │ /usr/src/app/models/base.py:60 in predict       │
                             │                                                 │
                             │    57 │   │   self.load()                       │
                             │    58 │   │   if model_kwargs:                  │
                             │    59 │   │   │   self.configure(**model_kwargs │
                             │ ❱  60 │   │   return self._predict(inputs)      │
                             │    61 │                                         │
                             │    62 │   @abstractmethod                       │
                             │    63 │   def _predict(self, inputs: Any) -> An │
                             │                                                 │
                             │ /usr/src/app/models/facial_recognition.py:49 in │
                             │ _predict                                        │
                             │                                                 │
                             │   46 │   │   else:                              │
                             │   47 │   │   │   decoded_image = image          │
                             │   48 │   │   assert is_ndarray(decoded_image, n │
                             │ ❱ 49 │   │   bboxes, kpss = self.det_model.dete │
                             │   50 │   │   if bboxes.size == 0:               │
                             │   51 │   │   │   return []                      │
                             │   52 │   │   assert is_ndarray(kpss, np.float32 │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/insightf │
                             │ ace/model_zoo/retinaface.py:224 in detect       │
                             │                                                 │
                             │   221 │   │   det_img = np.zeros( (input_size[1 │
                             │   222 │   │   det_img[:new_height, :new_width,  │
                             │   223 │   │                                     │
                             │ ❱ 224 │   │   scores_list, bboxes_list, kpss_li │
                             │   225 │   │                                     │
                             │   226 │   │   scores = np.vstack(scores_list)   │
                             │   227 │   │   scores_ravel = scores.ravel()     │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/insightf │
                             │ ace/model_zoo/retinaface.py:152 in forward      │
                             │                                                 │
                             │   149 │   │   kpss_list = []                    │
                             │   150 │   │   input_size = tuple(img.shape[0:2] │
                             │   151 │   │   blob = cv2.dnn.blobFromImage(img, │
                             │       (self.input_mean, self.input_mean, self.i │
                             │ ❱ 152 │   │   net_outs = self.session.run(self. │
                             │   153 │   │                                     │
                             │   154 │   │   input_height = blob.shape[2]      │
                             │   155 │   │   input_width = blob.shape[3]       │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:22 │
                             │ 0 in run                                        │
                             │                                                 │
                             │    217 │   │   if not output_names:             │
                             │    218 │   │   │   output_names = [output.name  │
                             │    219 │   │   try:                             │
                             │ ❱  220 │   │   │   return self._sess.run(output │
                             │    221 │   │   except C.EPFail as err:          │
                             │    222 │   │   │   if self._enable_fallback:    │
                             │    223 │   │   │   │   print(f"EP Error: {err!s │
                             ╰─────────────────────────────────────────────────╯
                             Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero     
                             status code returned while running Resize node.    
                             Name:'Resize_124' Status Message: CUDA error       
                             cudaErrorNoKernelImageForDevice:no kernel image is 
                             available for execution on the device              
2024-03-20 10:49:49.094414711 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Resize node. Name:'Resize_124' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

```

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS

### Version of Immich Server

1.98.2

### Version of Immich Mobile App

1.98.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=123password987
# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Install Nvidia drivers: https://ubuntu.com/server/docs/nvidia-drivers-installation
2. Install Nvidia Toolkit: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
3. Test [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/sample-workload.html) passes
4. Install Immich: https://immich.app/docs/install/docker-compose
5. Edit docker-compose: https://immich.app/docs/features/ml-hardware-acceleration
6. Upload from mobile app some photos and videos
7. Tried others ML models
```

**Comment by mertalev** [comment]
I believe your GPU’s compute capability is too low. It needs to be 5.2 or higher.

**Reply by 10Andrea10** [reply]
The only thing I found googling the error is that my GPU may not be supported by the latest pytorch. But I am not sure pytorch is even used here in ML. I expected it to work since CUDA runs fine, even if it has a low compute capability.

**Reply by mertalev** [reply]
We don't use PyTorch, but it's the same for ONNX Runtime: it targets certain compute capabilities and your GPU isn't targeted. It won't work without a custom build that targets your GPU's compute capability.

**Reply by 10Andrea10** [reply]
Oh okay thanks now makes sense. Is there any reference you can give me to try and build ONNX by myself lowering the target compute capability and include it in the ML docker image?

**Reply by mertalev** [reply]
You can look at their build [Dockerfile](https://github.com/microsoft/onnxruntime/blob/main/dockerfiles/Dockerfile.cuda) and add 50 to `CMAKE_CUDA_ARCHITECTURES`. You can then modify the ML Dockerfile to use this ONNX Runtime build. But it may or may not work - there may be a reason they don't target 5.0 anymore.

**Reply by andy2301** [reply]
I encountered the same error. @10Andrea10 Did you happen to make it work by adding 50 to CMAKE_CUDA_ARCHITECTURES as suggested? Thanks.

**Reply by sumitgpt** [reply]
I too encountered the same error. @10Andrea10 Did lowering the target compute capability work?

**Reply by 10Andrea10** [reply]
Unfortunately, I did not try to modify the Dockerfile and ended up using the CPU. If you managed to do that, feel free to share it.

**Reply by ricardomga** [reply]
@mertalev can you give me more detailed steps on how to do that? My GPU only has a compute capability of 5.0 but I would like to be able to use it still.

**Comment by Barrow1990** [comment]
What was the solution to this.
I have a 750 Ti & K620 that I want to use. Both are 5.0

**Comment by Magicrafter13** [comment]
I'm getting this issue with my GTX 970 all of a sudden (compute 5.2). Must've been something in a recent update. Maybe I need an older Nvidia driver?

**Reply by Barrow1990** [reply]
To fix it for me I used the legacy driver. This resolved it
