### ISSUE TITLE
immich-ml giving me errors since upgrading to latest today.

### ISSUE THREAD

**Issue by JayCroghan** [immich-app/immich#20496]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I updated containers for immich-ml and immich itself today on different machines, ml runs on a GPU machine, and I am getting the following error in immich-ml. The only thing I have changed since the last update is I installed the latest Nvidia CUDA Toolkit.

### The OS that Immich Server is running on

Ubuntu 20.04.05 LTS

### Version of Immich Server

v1.137.1 (same as immich-ml)

### Version of Immich Mobile App

v1.137.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich_remote_ml

services:
    immich-machine-learning:
      container_name: immich_machine_learning
      # Note the `-cuda` at the end
      image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
      # Note the lack of an `extends` section
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities:
                  - gpu
      volumes:
        #- "C:\Code\Immich-ML\cache:/cache"
        # ...
        - type: bind
          source: ./cache
          target: /cache
      restart: always
      ports:
        - 3003:3003
```

### Your .env content

```Shell
no .env
```

### Reproduction steps

1. Run any of the jobs requiring Immich-ML
2. Check logs
...

### Relevant log output

```shell
2025-08-01 11:23:18


                             │                                                 │
2025-08-01 11:23:18


                             │   28 │                                          │
2025-08-01 11:23:18


                             │   29 │   def _predict(self, inputs: Image.Image │
2025-08-01 11:23:18


                             │   30 │   │   image = decode_pil(inputs)         │
2025-08-01 11:23:18


                             │ ❱ 31 │   │   res: NDArray[np.float32] = self.se │
2025-08-01 11:23:18


                             │   32 │   │   return serialize_np_array(res)     │
2025-08-01 11:23:18


                             │   33 │                                          │
2025-08-01 11:23:18


                             │   34 │   @abstractmethod                        │
2025-08-01 11:23:18


                             │                                                 │
2025-08-01 11:23:18


                             │ /usr/src/immich_ml/sessions/ort.py:49 in run    │
2025-08-01 11:23:18


                             │                                                 │
2025-08-01 11:23:18


                             │    46 │   │   input_feed: dict[str, NDArray[np. │
2025-08-01 11:23:18


                             │    47 │   │   run_options: Any = None,          │
2025-08-01 11:23:18


                             │    48 │   ) -> list[NDArray[np.float32]]:       │
2025-08-01 11:23:18


                             │ ❱  49 │   │   outputs: list[NDArray[np.float32] │
2025-08-01 11:23:18


                             │       run_options)                              │
2025-08-01 11:23:18


                             │    50 │   │   return outputs                    │
2025-08-01 11:23:18


                             │    51 │                                         │
2025-08-01 11:23:18


                             │    52 │   @property                             │
2025-08-01 11:23:18


                             │                                                 │
2025-08-01 11:23:18


                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
2025-08-01 11:23:18


                             │ ime/capi/onnxruntime_inference_collection.py:22 │
2025-08-01 11:23:18


                             │ 0 in run                                        │
2025-08-01 11:23:18


                             │                                                 │
2025-08-01 11:23:18


                             │    217 │   │   if not output_names:             │
2025-08-01 11:23:18


                             │    218 │   │   │   output_names = [output.name  │
2025-08-01 11:23:18


                             │    219 │   │   try:                             │
2025-08-01 11:23:18


                             │ ❱  220 │   │   │   return self._sess.run(output │
2025-08-01 11:23:18


                             │    221 │   │   except C.EPFail as err:          │
2025-08-01 11:23:18


                             │    222 │   │   │   if self._enable_fallback:    │
2025-08-01 11:23:18


                             │    223 │   │   │   │   print(f"EP Error: {err!s │
2025-08-01 11:23:18


                             ╰─────────────────────────────────────────────────╯
2025-08-01 11:23:18


                             Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero     
2025-08-01 11:23:18


                             status code returned while running Conv node.      
2025-08-01 11:23:18


                             Name:'/visual/conv1/Conv' Status Message: CUDA     
2025-08-01 11:23:18


                             error cudaErrorStreamCaptureUnsupported:operation  
2025-08-01 11:23:18


                             not permitted when stream is capturing
```

**Comment by JayCroghan** [comment]
I tried taking a few photos and the error only happened that one time, maybe because I clicked 'Run Missing' on multiple jobs at once after the update when I uploaded a batch of new photos?

**Comment by gdechene** [comment]
I have the same issue. The logs of the server:

<img width="1477" height="626" alt="Image" src="https://github.com/user-attachments/assets/849c5b41-2049-4e38-babf-c4e0d3b15317" />

**Comment by gdechene** [comment]
I relaunched a smart search and it works!

**Comment by Talhamehar007** [comment]
I have the same issue, the server refuses to start after I upgraded to v1.137.1, I had to revert back to v.1.137.0 for now o fix. Change your version value in your .env file, unless the bug s fixed

**Comment by sneak-it** [comment]
Adding a +1 to this here, went to run a search and it had failed, similar error. Relaunched ML container but that's obviously not a solution. Latest version 1.141.1.

```
2025-09-12 15:23:55.068057233 [E:onnxruntime:, inference_session.cc:2105 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 9437184
[m
[09/12/25 15:23:55] ERROR    Exception in ASGI application                      
                                                                                
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/immich_ml/main.py:177 in predict       │
                             │                                                 │
                             │   174 │   │   inputs = text                     │
                             │   175 │   else:                                 │
                             │   176 │   │   raise HTTPException(400, "Either  │
                             │ ❱ 177 │   response = await run_inference(inputs │
                             │   178 │   return ORJSONResponse(response)       │
                             │   179                                           │
                             │   180                                           │
                             │                                                 │
                             │ /usr/src/immich_ml/main.py:200 in run_inference │
                             │                                                 │
                             │   197 │   │   response[entry["task"]] = output  │
                             │   198 │                                         │
                             │   199 │   without_deps, with_deps = entries     │
                             │ ❱ 200 │   await asyncio.gather(*[_run_inference │
                             │   201 │   if with_deps:                         │
                             │   202 │   │   await asyncio.gather(*[_run_infer │
                             │   203 │   if isinstance(payload, Image):        │
                             │                                                 │
                             │ /usr/src/immich_ml/main.py:194 in               │
                             │ _run_inference                                  │
                             │                                                 │
                             │   191 │   │   │   except KeyError:              │
                             │   192 │   │   │   │   message = f"Task {entry[' │
                             │       output of {dep}"                          │
                             │   193 │   │   │   │   raise HTTPException(400,  │
                             │ ❱ 194 │   │   model = await load(model)         │
                             │   195 │   │   output = await run(model.predict, │
                             │   196 │   │   outputs[model.identity] = output  │
                             │   197 │   │   response[entry["task"]] = output  │
                             │                                                 │
                             │ /usr/src/immich_ml/main.py:238 in load          │
                             │                                                 │
                             │   235 │   │   return model                      │
                             │   236 │                                         │
                             │   237 │   try:                                  │
                             │ ❱ 238 │   │   return await run(_load, model)    │
                             │   239 │   except (OSError, InvalidProtobuf, Bad │
                             │   240 │   │   log.warning(f"Failed to load {mod │
                             │       '{model.model_name}'. Clearing cache.")   │
                             │   241 │   │   model.clear_cache()               │
                             │                                                 │
                             │ /usr/src/immich_ml/main.py:213 in run           │
                             │                                                 │
                             │   210 │   if thread_pool is None:               │
                             │   211 │   │   return func(*args, **kwargs)      │
                             │   212 │   partial_func = partial(func, *args, * │
                             │ ❱ 213 │   return await asyncio.get_running_loop │
                             │   214                                           │
                             │   215                                           │
                             │   216 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ /usr/local/lib/python3.11/concurrent/futures/th │
                             │ read.py:58 in run                               │
                             │                                                 │
                             │ /usr/src/immich_ml/main.py:225 in _load         │
                             │                                                 │
                             │   222 │   │   │   raise HTTPException(500, f"Fa │
                             │   223 │   │   with lock:                        │
                             │   224 │   │   │   try:                          │
                             │ ❱ 225 │   │   │   │   model.load()              │
                             │   226 │   │   │   except FileNotFoundError as e │
                             │   227 │   │   │   │   if model.model_format ==  │
                             │   228 │   │   │   │   │   raise e               │
                             │                                                 │
                             │ /usr/src/immich_ml/models/base.py:54 in load    │
                             │                                                 │
                             │    51 │   │   self.download()                   │
                             │    52 │   │   attempt = f"Attempt #{self.load_a │
                             │       else "Loading"                            │
                             │    53 │   │   log.info(f"{attempt} {self.model_ │
                             │       '{self.model_name}' to memory")           │
                             │ ❱  54 │   │   self.session = self._load()       │
                             │    55 │   │   self.loaded = True                │
                             │    56 │                                         │
                             │    57 │   def predict(self, *inputs: Any, **mod │
                             │                                                 │
                             │ /usr/src/immich_ml/models/clip/textual.py:28 in │
                             │ _load                                           │
                             │                                                 │
                             │    25 │   │   return serialize_np_array(res)    │
                             │    26 │                                         │
                             │    27 │   def _load(self) -> ModelSession:      │
                             │ ❱  28 │   │   session = super()._load()         │
                             │    29 │   │   log.debug(f"Loading tokenizer for │
                             │    30 │   │   self.tokenizer = self._load_token │
                             │    31 │   │   tokenizer_kwargs: dict[str, Any]  │
                             │                                                 │
                             │ /usr/src/immich_ml/models/base.py:84 in _load   │
                             │                                                 │
                             │    81 │   │   )                                 │
                             │    82 │                                         │
                             │    83 │   def _load(self) -> ModelSession:      │
                             │ ❱  84 │   │   return self._make_session(self.mo │
                             │    85 │                                         │
                             │    86 │   def clear_cache(self) -> None:        │
                             │    87 │   │   if not self.cache_dir.exists():   │
                             │                                                 │
                             │ /usr/src/immich_ml/models/base.py:116 in        │
                             │ _make_session                                   │
                             │                                                 │
                             │   113 │   │   │   case ".armnn":                │
                             │   114 │   │   │   │   session: ModelSession = A │
                             │   115 │   │   │   case ".onnx":                 │
                             │ ❱ 116 │   │   │   │   session = OrtSession(mode │
                             │   117 │   │   │   case ".rknn":                 │
                             │   118 │   │   │   │   session = rknn.RknnSessio │
                             │   119 │   │   │   case _:                       │
                             │                                                 │
                             │ /usr/src/immich_ml/sessions/ort.py:28 in        │
                             │ __init__                                        │
                             │                                                 │
                             │    25 │   │   self.providers = providers if pro │
                             │    26 │   │   self.provider_options = provider_ │
                             │       self._provider_options_default            │
                             │    27 │   │   self.sess_options = sess_options  │
                             │       self._sess_options_default                │
                             │ ❱  28 │   │   self.session = ort.InferenceSessi │
                             │    29 │   │   │   self.model_path.as_posix(),   │
                             │    30 │   │   │   providers=self.providers,     │
                             │    31 │   │   │   provider_options=self.provide │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:41 │
                             │ 9 in __init__                                   │
                             │                                                 │
                             │    416 │   │   disabled_optimizers = kwargs.get │
                             │    417 │   │                                    │
                             │    418 │   │   try:                             │
                             │ ❱  419 │   │   │   self._create_inference_sessi │
                             │        disabled_optimizers)                     │
                             │    420 │   │   except (ValueError, RuntimeError │
                             │    421 │   │   │   if self._enable_fallback:    │
                             │    422 │   │   │   │   try:                     │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:49 │
                             │ 1 in _create_inference_session                  │
                             │                                                 │
                             │    488 │   │   │   disabled_optimizers = set(di │
                             │    489 │   │                                    │
                             │    490 │   │   # initialize the C++ InferenceSe │
                             │ ❱  491 │   │   sess.initialize_session(provider │
                             │    492 │   │                                    │
                             │    493 │   │   self._sess = sess                │
                             │    494 │   │   self._sess_options = self._sess. │
                             ╰─────────────────────────────────────────────────╯
                             RuntimeException: [ONNXRuntimeError] : 6 :         
                             RUNTIME_EXCEPTION : Exception during               
                             initialization:                                    
                             /onnxruntime_src/onnxruntime/core/framework/bfc_are
                             na.cc:376 void*                                    
                             onnxruntime::BFCArena::AllocateRawInternal(size_t, 
                             bool, onnxruntime::Stream*, bool,                  
                             onnxruntime::WaitNotificationFn) Failed to allocate
                             memory for requested buffer of size 9437184
```


Seems to attempt to load model again and fails with the same error.

**Comment by haoxi911** [comment]
When the error "CUDA failure 2: out of memory" raised, my 128GB RAM GPU shows 100% in use. I am wondering if it could be a memory leak issue in ML container.

```
immich_machine_learning  | [10/03/25 13:59:02] ERROR    Exception in ASGI application                      
immich_machine_learning  |                                                                                 
immich_machine_learning  |                              ╭─────── Traceback (most recent call last) ───────╮
immich_machine_learning  |                              │ /usr/src/immich_ml/main.py:177 in predict       │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   174 │   │   inputs = text                     │
immich_machine_learning  |                              │   175 │   else:                                 │
immich_machine_learning  |                              │   176 │   │   raise HTTPException(400, "Either  │
immich_machine_learning  |                              │ ❱ 177 │   response = await run_inference(inputs │
immich_machine_learning  |                              │   178 │   return ORJSONResponse(response)       │
immich_machine_learning  |                              │   179                                           │
immich_machine_learning  |                              │   180                                           │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /usr/src/immich_ml/main.py:202 in run_inference │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   199 │   without_deps, with_deps = entries     │
immich_machine_learning  |                              │   200 │   await asyncio.gather(*[_run_inference │
immich_machine_learning  |                              │   201 │   if with_deps:                         │
immich_machine_learning  |                              │ ❱ 202 │   │   await asyncio.gather(*[_run_infer │
immich_machine_learning  |                              │   203 │   if isinstance(payload, Image):        │
immich_machine_learning  |                              │   204 │   │   response["imageHeight"], response │
immich_machine_learning  |                              │   205                                           │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /usr/src/immich_ml/main.py:195 in               │
immich_machine_learning  |                              │ _run_inference                                  │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   192 │   │   │   │   message = f"Task {entry[' │
immich_machine_learning  |                              │       output of {dep}"                          │
immich_machine_learning  |                              │   193 │   │   │   │   raise HTTPException(400,  │
immich_machine_learning  |                              │   194 │   │   model = await load(model)         │
immich_machine_learning  |                              │ ❱ 195 │   │   output = await run(model.predict, │
immich_machine_learning  |                              │   196 │   │   outputs[model.identity] = output  │
immich_machine_learning  |                              │   197 │   │   response[entry["task"]] = output  │
immich_machine_learning  |                              │   198                                           │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /usr/src/immich_ml/main.py:213 in run           │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   210 │   if thread_pool is None:               │
immich_machine_learning  |                              │   211 │   │   return func(*args, **kwargs)      │
immich_machine_learning  |                              │   212 │   partial_func = partial(func, *args, * │
immich_machine_learning  |                              │ ❱ 213 │   return await asyncio.get_running_loop │
immich_machine_learning  |                              │   214                                           │
immich_machine_learning  |                              │   215                                           │
immich_machine_learning  |                              │   216 async def load(model: InferenceModel) ->  │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /usr/local/lib/python3.11/concurrent/futures/th │
immich_machine_learning  |                              │ read.py:58 in run                               │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /usr/src/immich_ml/models/base.py:61 in predict │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │    58 │   │   self.load()                       │
immich_machine_learning  |                              │    59 │   │   if model_kwargs:                  │
immich_machine_learning  |                              │    60 │   │   │   self.configure(**model_kwargs │
immich_machine_learning  |                              │ ❱  61 │   │   return self._predict(*inputs, **m │
immich_machine_learning  |                              │    62 │                                         │
immich_machine_learning  |                              │    63 │   @abstractmethod                       │
immich_machine_learning  |                              │    64 │   def _predict(self, *inputs: Any, **mo │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /usr/src/immich_ml/models/facial_recognition/re │
immich_machine_learning  |                              │ cognition.py:53 in _predict                     │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   50 │   │   │   return []                      │
immich_machine_learning  |                              │   51 │   │   inputs = decode_cv2(inputs)        │
immich_machine_learning  |                              │   52 │   │   cropped_faces = self._crop(inputs, │
immich_machine_learning  |                              │ ❱ 53 │   │   embeddings = self._predict_batch(c │
immich_machine_learning  |                              │   54 │   │   return self.postprocess(faces, emb │
immich_machine_learning  |                              │   55 │                                          │
immich_machine_learning  |                              │   56 │   def _predict_batch(self, cropped_faces │
immich_machine_learning  |                              │      NDArray[np.float32]:                       │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /usr/src/immich_ml/models/facial_recognition/re │
immich_machine_learning  |                              │ cognition.py:58 in _predict_batch               │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   55 │                                          │
immich_machine_learning  |                              │   56 │   def _predict_batch(self, cropped_faces │
immich_machine_learning  |                              │      NDArray[np.float32]:                       │
immich_machine_learning  |                              │   57 │   │   if not self.batch_size or len(crop │
immich_machine_learning  |                              │ ❱ 58 │   │   │   embeddings: NDArray[np.float32 │
immich_machine_learning  |                              │   59 │   │   │   return embeddings              │
immich_machine_learning  |                              │   60 │   │                                      │
immich_machine_learning  |                              │   61 │   │   batch_embeddings: list[NDArray[np. │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /opt/venv/lib/python3.11/site-packages/insightf │
immich_machine_learning  |                              │ ace/model_zoo/arcface_onnx.py:84 in get_feat    │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   81 │   │                                      │
immich_machine_learning  |                              │   82 │   │   blob = cv2.dnn.blobFromImages(imgs │
immich_machine_learning  |                              │   83 │   │   │   │   │   │   │   │   │     (sel │
immich_machine_learning  |                              │      self.input_mean), swapRB=True)             │
immich_machine_learning  |                              │ ❱ 84 │   │   net_out = self.session.run(self.ou │
immich_machine_learning  |                              │   85 │   │   return net_out                     │
immich_machine_learning  |                              │   86 │                                          │
immich_machine_learning  |                              │   87 │   def forward(self, batch_data):         │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /usr/src/immich_ml/sessions/ort.py:49 in run    │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │    46 │   │   input_feed: dict[str, NDArray[np. │
immich_machine_learning  |                              │    47 │   │   run_options: Any = None,          │
immich_machine_learning  |                              │    48 │   ) -> list[NDArray[np.float32]]:       │
immich_machine_learning  |                              │ ❱  49 │   │   outputs: list[NDArray[np.float32] │
immich_machine_learning  |                              │       run_options)                              │
immich_machine_learning  |                              │    50 │   │   return outputs                    │
immich_machine_learning  |                              │    51 │                                         │
immich_machine_learning  |                              │    52 │   @property                             │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
immich_machine_learning  |                              │ ime/capi/onnxruntime_inference_collection.py:22 │
immich_machine_learning  |                              │ 0 in run                                        │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │    217 │   │   if not output_names:             │
immich_machine_learning  |                              │    218 │   │   │   output_names = [output.name  │
immich_machine_learning  |                              │    219 │   │   try:                             │
immich_machine_learning  |                              │ ❱  220 │   │   │   return self._sess.run(output │
immich_machine_learning  |                              │    221 │   │   except C.EPFail as err:          │
immich_machine_learning  |                              │    222 │   │   │   if self._enable_fallback:    │
immich_machine_learning  |                              │    223 │   │   │   │   print(f"EP Error: {err!s │
immich_machine_learning  |                              ╰─────────────────────────────────────────────────╯
immich_machine_learning  |                              RuntimeException: [ONNXRuntimeError] : 6 :         
immich_machine_learning  |                              RUNTIME_EXCEPTION : Non-zero status code returned  
immich_machine_learning  |                              while running Conv node. Name:'Conv_9' Status      
immich_machine_learning  |                              Message:                                           
immich_machine_learning  |                              /onnxruntime_src/onnxruntime/core/providers/cuda/cu
immich_machine_learning  |                              da_call.cc:123 std::conditional_t<THRW, void,      
immich_machine_learning  |                              onnxruntime::common::Status>                       
immich_machine_learning  |                              onnxruntime::CudaCall(ERRTYPE, const char*, const  
immich_machine_learning  |                              char*, ERRTYPE, const char*, const char*, int)     
immich_machine_learning  |                              [with ERRTYPE = cudaError; bool THRW = true;       
immich_machine_learning  |                              std::conditional_t<THRW, void, common::Status> =   
immich_machine_learning  |                              void]                                              
immich_machine_learning  |                              /onnxruntime_src/onnxruntime/core/providers/cuda/cu
immich_machine_learning  |                              da_call.cc:116 std::conditional_t<THRW, void,      
immich_machine_learning  |                              onnxruntime::common::Status>                       
immich_machine_learning  |                              onnxruntime::CudaCall(ERRTYPE, const char*, const  
immich_machine_learning  |                              char*, ERRTYPE, const char*, const char*, int)     
immich_machine_learning  |                              [with ERRTYPE = cudaError; bool THRW = true;       
immich_machine_learning  |                              std::conditional_t<THRW, void, common::Status> =   
immich_machine_learning  |                              void] CUDA failure 2: out of memory ; GPU=0 ;      
immich_machine_learning  |                              hostname=50481096b539 ;                            
immich_machine_learning  |                              file=/onnxruntime_src/onnxruntime/core/providers/cu
immich_machine_learning  |                              da/cuda_allocator.cc ; line=47 ;                   
immich_machine_learning  |                              expr=cudaMalloc((void**)&p, size);                 
```

**Comment by TCNOco** [comment]
I had a very similar issue to the first error. I unfortunately only saved the start and end of the error message. Spacing also got a little sad:
```
*************** EP Error ***************
EP Error: 
/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:123
std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(
    ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int
) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, common::Status> = void]

/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116
std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(
    ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int
) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, common::Status> = void]

CUDA failure 900: operation not permitted when stream is capturing
GPU=0 ; hostname=32f49ec156d6 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_p
rovider.cc ; line=283 ; expr=cudaDeviceSynchronize();

When using: ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to: ['CPUExecutionProvider'] and retrying.
****************************************

[10/09/25 02:58:57] INFO     Loading recognition model 'buffalo_l' to memory
[10/09/25 02:58:57] INFO     Setting execution providers to ['CUDAExecution
Provider', 'CPUExecutionProvider'], in descending order of preference
2025-10-09 02:58:58.150138407 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel]
Non-zero status code returned while running FusedConv node. Name:'Conv_0'
Status Message: CUDA error cudaErrorStreamCaptureUnsupported:
operation not permitted when stream is capturing

...

[10/09/25 02:58:58] ERROR    Exception in ASGI application Fail:
[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node.
Name:'Conv_0' Status Message: CUDA error cudaErrorStreamCaptureUnsupported:
operation not permitted when stream is capturing    
```

Since docker down and up -d I lost the original logs, sadly.

I was able to fix this by adding the following to my immich-machine-learning service in its docker-compose.yml:
```yml
environment:
      - EXTRA_ARGS=--disable-cuda-graph
```

I got this from Grok, but it worked, and now ML runs infinitely faster for my little NAS. The reasoning it gave:
Why This Works: The `--disable-cuda-graph` flag tells ONNX Runtime to skip CUDA graph capture, avoiding the `cudaErrorStreamCaptureUnsupported` error. This maintains GPU acceleration with a minor performance hit (~10-20%).

Version: `ghcr.io/immich-app/immich-machine-learning:release-cuda` aka [v2.0.1-cuda](https://github.com/orgs/immich-app/packages/container/immich-machine-learning/534280909?tag=v2.0.1-cuda)

**Comment by vrajpal-jhala** [comment]
> I was able to fix this by adding the following to my immich-machine-learning service in its docker-compose.yml:
> 
> environment:
>       - EXTRA_ARGS=--disable-cuda-graph
> I got this from Grok, but it worked, and now ML runs infinitely faster for my little NAS. The reasoning it gave: Why This Works: The `--disable-cuda-graph` flag tells ONNX Runtime to skip CUDA graph capture, avoiding the `cudaErrorStreamCaptureUnsupported` error. This maintains GPU acceleration with a minor performance hit (~10-20%).
> 
> Version: `ghcr.io/immich-app/immich-machine-learning:release-cuda` aka [v2.0.1-cuda](https://github.com/orgs/immich-app/packages/container/immich-machine-learning/534280909?tag=v2.0.1-cuda)

This works for me as well (same release). Thanks!

**Comment by daftu** [comment]
For me adding --disable-cuda-graph for v2.1.0 didn't help (ghcr.io/immich-app/immich-machine-learning:v2.1.0-cuda)

**Comment by darkphox** [comment]
> For me adding --disable-cuda-graph for v2.1.0 didn't help (ghcr.io/immich-app/immich-machine-learning:v2.1.0-cuda)

What's your job concurrency set to? I added "disable-cuda-graph" and it didn't work for me either at first. However, I had also set a higher concurrency for the OCR jobs.

I reset the concurrency back to "1" and it's been using GPU with no more errors. I'm running the "server" model on an RTX 3090 and I'm seeing GPU load fluctuate up to 100% with memory usage at 48-53%. I tried increasing concurrency to 2 and the error started again within a few seconds.

**Comment by daftu** [comment]
> What's your job concurrency set to? I added "disable-cuda-graph" and it didn't work for me either at first. However, I had also set a higher concurrency for the OCR jobs.
> 
> I reset the concurrency back to "1" and it's been using GPU with no more errors. I'm running the "server" model on an RTX 3090 and I'm seeing GPU load fluctuate up to 100% with memory usage at 48-53%. I tried increasing concurrency to 2 and the error started again within a few seconds.

My job concurrency for OCR is and was set to "1".

**Comment by Aunali321** [comment]
I ran into the same issue with the CUDA stream capture errors on my RTX 5070 Ti. The `EXTRA_ARGS=--disable-cuda-graph` environment variable doesn't actually work because the codebase doesn't read it.

Here's what fixed it for me:

```bash
docker exec immich_machine_learning sed -i 's/"device_id": settings.device_id}/"device_id": settings.device_id, "enable_cuda_graph": False}/' /usr/src/immich_ml/sessions/ort.py
docker restart immich_machine_learning
```

This patches the ONNX Runtime session config to disable CUDA graphs directly in the provider options. After restarting, all models load on GPU without errors.

Just a heads up - this only works until you recreate the container (docker compose down/up). You'll need to reapply the patch each time or build a custom image.

GPU utilization jumped to 80%+ during ML jobs and everything processes way faster now. Hope this helps someone else hitting the same issue.

**Comment by LeonNamowitz** [comment]
> Here's what fixed it for me:
> 
> docker exec immich_machine_learning sed -i 's/"device_id": settings.device_id}/"device_id": settings.device_id, "enable_cuda_graph": False}/' /usr/src/immich_ml/sessions/ort.py
> docker restart immich_machine_learning
> This patches the ONNX Runtime session config to disable CUDA graphs directly in the provider options. After restarting, all models load on GPU without errors.
> 
> Just a heads up - this only works until you recreate the container (docker compose down/up). You'll need to reapply the patch each time or build a custom image.
> 
> GPU utilization jumped to 80%+ during ML jobs and everything processes way faster now. Hope this helps someone else hitting the same issue.

None of this makes a difference for me. 
If I do that, this is what my VRAM usage looks like on my 4080 immediately after container start.

<img width="464" height="143" alt="Image" src="https://github.com/user-attachments/assets/493d22f1-3f66-40bb-a1bd-cbcdbe332837" />

<img width="470" height="130" alt="Image" src="https://github.com/user-attachments/assets/27c944b1-2a2f-4ab9-9098-31ac7121eac6" />

Then it stays at ~16200, my RAM increases by about 10GB and then the OCR progress just stops in Immich, I don't even get any more errors in the ML container.

Otherwise the same error as everyone else.

**Comment by zdimension** [comment]
Encountering this too on my 1060 whenever I set the concurrency to > 1.

**Comment by coldsprinkles** [comment]
+1

**Comment by krojew** [comment]
Fresh install, ran into this error on a 3060.

**Comment by lastb0isct** [comment]
Fresh installation and getting the same error on my system...

**Comment by foreword101** [comment]
Fresh install same issue, however running a p620, so ram may be limitation.

**Comment by roadhazard** [comment]
Running Immich in a Docker on bare metal Debian 13 and noticed that my Nvidia RTX 4000 (Turing) GPU wasn't being used. Was getting the same error as a lot of you:

`immich_machine_learning  | *************** EP Error ***************
immich_machine_learning  | EP Error /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:123 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, common::Status> = void] CUDA failure 900: operation not permitted when stream is capturing ; GPU=0 ; hostname=9799a8ce3303 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=283 ; expr=cudaDeviceSynchronize(); 
immich_machine_learning  | 
immich_machine_learning  |  when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
immich_machine_learning  | Falling back to ['CPUExecutionProvider'] and retrying.
immich_machine_learning  | ****************************************
`

Adding this:

`
environment:
      - EXTRA_ARGS=--disable-cuda-graph
`

... fixed it for me.
