### ISSUE TITLE
ML CUDA image (release-cuda) fails on Blackwell GPUs (RTX 50-series, sm_120) — base image is CUDA 12.2, needs 12.8+

### ISSUE THREAD

**Issue by ekropotin** [immich-app/immich#28583]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

The `ghcr.io/immich-app/immich-machine-learning:release-cuda` image cannot initialize CUDA on Blackwell GPUs (RTX 50-series, compute capability `sm_120`). ONNX Runtime fails with `CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version`, the CUDA execution provider is dropped, and all ML jobs (CLIP embeddings, face detection) silently run on CPU instead of GPU. GPU passthrough is healthy — `nvidia-smi` inside the container shows the GPU.

**Root cause:** the `prod-cuda` Dockerfile stage is built on `nvidia/cuda:12.2.2-runtime-ubuntu22.04`. CUDA 12.2 predates Blackwell — `sm_120` support landed in CUDA 12.8 (Feb 2025). When ORT queries the device's compute capability and gets `12.0`, the 12.2 runtime does not recognise it.

```
$ nvidia-smi --query-gpu=name,compute_cap --format=csv,noheader
NVIDIA GeForce RTX 5060 Ti, 12.0
```

**Previous attempts at upstream tracking:**

- PR [#28032](https://github.com/immich-app/immich/pull/28032) — proposed the base-image bump; closed by @bo0tzz with "we prefer not to merge manual version bumps … this has surfaced an issue with our renovate configuration … I'll get that fixed." No public tracking link for that follow-up; my request for one went unanswered.
- Discussion [#10647](https://github.com/immich-app/immich/discussions/10647) — adjacent, but scoped to arm64 image manifest (Jetson / DGX Spark). Reopening the conversation under this template seems to be the only avenue still open.

### Why a naive base-image bump isn't quite enough

The `prod-cuda` stage installs `libcudnn9-cuda-12=9.10.2.21-1` (pinned at 9.10 because 9.11 drops Pascal). Its apt dependency chain drags in `cuda-cudart-12-2` / `cuda-libraries-12-2` and runs `update-alternatives`, silently re-pointing `/usr/local/cuda → /usr/local/cuda-12.2/` and leaving the image effectively back on CUDA 12.2. `apt-get autoremove` in the later `prod` stage re-triggers `update-alternatives`, so even an explicit `ln -sfn` or `update-alternatives --set` in `prod-cuda` gets overridden.

A working mitigation (running in production on my fork): bump the base to `nvidia/cuda:12.8.1-runtime-ubuntu22.04`, then after cuDNN install explicitly reinstall `cuda-cudart-12-8`, `apt-mark manual` it so autoremove doesn't strip it, and re-pin the symlink as a guard in the final `prod` stage.

- Fork (working image): https://github.com/ekropotin/immich
- [Diff](https://github.com/immich-app/immich/compare/main...ekropotin:immich:fix/cuda-blackwell-support#diff-dae4a213ec543902f9266c7de0ffa7950ea3f61c9b5d38bfc820708b1a32cf5b)

### The OS that Immich Server is running on

NixOS

### Version of Immich Server

2.7.5

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

### Your .env content

Irrelevant, but:

```Shell
DB_PASSWORD=<redacted>
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
UPLOAD_LOCATION=/var/lib/immich/upload
IMMICH_VERSION=release
IMMICH_MACHINE_LEARNING_URL=http://immich_machine_learning:3003
```

### Reproduction steps

1. On a host with an NVIDIA RTX 50-series GPU (Blackwell, sm_120) and driver ≥570, install the NVIDIA Container Toolkit and verify `nvidia-smi` works inside a test container (`docker run --rm --gpus all nvidia/cuda:12.8.1-base-ubuntu22.04 nvidia-smi`).
2. Deploy Immich using the upstream `docker-compose.yml` plus the CUDA override: `docker compose -f docker-compose.yml -f hwaccel.ml.yml --profile cuda up -d` (uses image `ghcr.io/immich-app/immich-machine-learning:release-cuda`).
3. Log into the web UI, upload a few photos, and wait for ML jobs to run (Smart Search / Face Detection). Or trigger them manually via Administration → Jobs → Smart Search → "All".
4. Observe:
   - `docker logs immich_machine_learning` shows `CUDA failure 35` and a fallback to `CPUExecutionProvider`.
   - `nvidia-smi` on the host shows 0% GPU utilisation while ML jobs run.
   - Jobs still complete (CPU path works), so the failure is silent from the end-user perspective unless logs are checked.

### Relevant log output

```shell
Setting execution providers to ['CUDAExecutionProvider', 'CPUExecutionProvider']
...
EP Error: Failed to parse provider option "device_id": ... cudaGetDeviceCount
CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version
...
Falling back to ['CPUExecutionProvider'] and retrying.
```

### Additional information

This affects more than just RTX 50-series desktops — the DGX Spark GB10 (Blackwell sm_121, arm64) hits the same family of issues as documented by @mARTin-B78 in #10647. Other affected users have surfaced in #28032 review and in the comments of #28031.

**Comment by bo0tzz** [comment]
> No public tracking link for that follow-up; my request for one went unanswered.

There was nothing to track, I just fixed it, renovate is properly bumping the base image these days.

**Comment by Tantrax007** [comment]
Good evening, everyone!

I just wanted to mention that I have the exact same problem, but I'm using Quadlets on AlmaLinux, and after trying to lower the graphics expectations with:
```bash
Environment=CUDA_MODULE_LOADING=LAZY
Environment=ORT_CUDA_UNAVAILABLE_FALLBACK=0
```
Nothing have ever workded...

**Comment by ekropotin** [comment]
@Tantrax007 you may want to check out the community fork image https://github.com/ekropotin/immich/pkgs/container/immich-machine-learning
As immediate remedy

**Comment by tomzorz** [comment]
Not sure if related, but on my GTX950 (so, ancient) I am getting:

```
['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
2026-06-17 19:32:55.190207570 [E:onnxruntime:Default, cuda_call.cc:123 CudaCall] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1 ; hostname=e2aa1ed7be6d ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc ; line=67 ; expr=cudaGetDeviceCount(&num_devices); 
*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc:60 static onnxruntime::CUDAExecutionProviderInfo onnxruntime::CUDAExecutionProviderInfo::FromProviderOptions(const onnxruntime::ProviderOptions&) [ONNXRuntimeError] : 1 : FAIL : provider_options_utils.h:187 Parse Failed to parse provider option "device_id": CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1 ; hostname=e2aa1ed7be6d ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc ; line=67 ; expr=cudaGetDeviceCount(&num_devices); 
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
```

so seemingly the same error, but different class of card. I recently upgraded to unraid 7.3 from 6.12, and reinstalled my server - I am also using the imagegenius docker. When I apply "--runtime=nvidia" the docker image does not start anymore:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error jailing process inside rootfs: open /proc/self/mountinfo: no such file or directory
```

**Comment by dh-nunes** [comment]
> Not sure if related, but on my GTX950 (so, ancient) I am getting:
> 
> ```
> ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
>                              in descending order of preference                  
> 2026-06-17 19:32:55.190207570 [E:onnxruntime:Default, cuda_call.cc:123 CudaCall] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1 ; hostname=e2aa1ed7be6d ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc ; line=67 ; expr=cudaGetDeviceCount(&num_devices); 
> *************** EP Error ***************
> EP Error /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc:60 static onnxruntime::CUDAExecutionProviderInfo onnxruntime::CUDAExecutionProviderInfo::FromProviderOptions(const onnxruntime::ProviderOptions&) [ONNXRuntimeError] : 1 : FAIL : provider_options_utils.h:187 Parse Failed to parse provider option "device_id": CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1 ; hostname=e2aa1ed7be6d ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc ; line=67 ; expr=cudaGetDeviceCount(&num_devices); 
>  when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
> ```
> 
> so seemingly the same error, but different class of card. I recently upgraded to unraid 7.3 from 6.12, and reinstalled my server - I am also using the imagegenius docker. When I apply "--runtime=nvidia" the docker image does not start anymore:
> 
> ```
> docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error jailing process inside rootfs: open /proc/self/mountinfo: no such file or directory
> ```

Exact same error on a new(ish) RTX 5060 Ti, running on docker on arch/cachyos, using the image from the docs EDIT: the same happens with the above community fork:

```
06/21/26 20:30:06] INFO     Setting execution providers to                     
                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
2026-06-21 20:30:07.297093145 [E:onnxruntime:Default, cuda_call.cc:123 CudaCall] CUDA failure 999: unknown error ; GPU=-1 ; hostname=7660fb6cd3b4 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc ; line=67 ; expr=cudaGetDeviceCount(&num_devices); 
*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc:60 static onnxruntime::CUDAExecutionProviderInfo onnxruntime::CUDAExecutionProviderInfo::FromProviderOptions(const onnxruntime::ProviderOptions&) [ONNXRuntimeError] : 1 : FAIL : provider_options_utils.h:187 Parse Failed to parse provider option "device_id": CUDA failure 999: unknown error ; GPU=-1 ; hostname=7660fb6cd3b4 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc ; line=67 ; expr=cudaGetDeviceCount(&num_devices); 
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
****************************************
/opt/venv/lib/python3.11/site-packages/fastapi/routing.py:328: FastAPIDeprecationWarning: ORJSONResponse is deprecated, FastAPI now serializes data directly to JSON bytes via Pydantic when a return type or response model is set, which is faster and doesn't need a custom response class. Read more in the FastAPI docs: https://fastapi.tiangolo.com/advanced/custom-response/#orjson-or-response-model and https://fastapi.tiangolo.com/tutorial/response-model/
  return await dependant.call(**values)
```

**Comment by Tantrax007** [comment]
Good evening everyone, after a month of use, I can confirm that I haven't had any problems with facial recognition using custom image from @ekropotin. However, there is one point I'd like to raise that's closely related to the following issue: https://github.com/immich-app/immich/issues/20496 but at least in my case, and because I haven't found anything related, my problem is:
```
#.....
                             │ /usr/local/lib/python3.11/pathlib.py:509 in     │
                             │ _from_parts                                     │
                             │                                                 │
                             │    506 │   │   # We need to call _parse_args on │
                             │    507 │   │   # right flavour.                 │
                             │    508 │   │   self = object.__new__(cls)       │
                             │ ❱  509 │   │   drv, root, parts = self._parse_a │
                             │    510 │   │   self._drv = drv                  │
                             │    511 │   │   self._root = root                │
                             │    512 │   │   self._parts = parts              │
                             │                                                 │
                             │ /usr/local/lib/python3.11/pathlib.py:493 in     │
                             │ _parse_args                                     │
                             │                                                 │
                             │    490 │   │   │   if isinstance(a, PurePath):  │
                             │    491 │   │   │   │   parts += a._parts        │
                             │    492 │   │   │   else:                        │
                             │ ❱  493 │   │   │   │   a = os.fspath(a)         │
                             │    494 │   │   │   │   if isinstance(a, str):   │
                             │    495 │   │   │   │   │   # Force-cast str sub │
                             │    496 │   │   │   │   │   parts.append(str(a)) │
                             ╰─────────────────────────────────────────────────╯
                             TypeError: expected str, bytes or os.PathLike      
                             object, not NoneType 
```

I'm currently working on a fix, in the meantime, if someone has any idea or had similar situation let's talk!

**Comment by Tantrax007** [comment]
> Good evening everyone, after a month of use, I can confirm that I haven't had any problems with facial recognition using custom image from [@ekropotin](https://github.com/ekropotin). However, there is one point I'd like to raise that's closely related to the following issue: [#20496](https://github.com/immich-app/immich/issues/20496) but at least in my case, and because I haven't found anything related, my problem is:
> 
> ```
> #.....
>                              │ /usr/local/lib/python3.11/pathlib.py:509 in     │
>                              │ _from_parts                                     │
>                              │                                                 │
>                              │    506 │   │   # We need to call _parse_args on │
>                              │    507 │   │   # right flavour.                 │
>                              │    508 │   │   self = object.__new__(cls)       │
>                              │ ❱  509 │   │   drv, root, parts = self._parse_a │
>                              │    510 │   │   self._drv = drv                  │
>                              │    511 │   │   self._root = root                │
>                              │    512 │   │   self._parts = parts              │
>                              │                                                 │
>                              │ /usr/local/lib/python3.11/pathlib.py:493 in     │
>                              │ _parse_args                                     │
>                              │                                                 │
>                              │    490 │   │   │   if isinstance(a, PurePath):  │
>                              │    491 │   │   │   │   parts += a._parts        │
>                              │    492 │   │   │   else:                        │
>                              │ ❱  493 │   │   │   │   a = os.fspath(a)         │
>                              │    494 │   │   │   │   if isinstance(a, str):   │
>                              │    495 │   │   │   │   │   # Force-cast str sub │
>                              │    496 │   │   │   │   │   parts.append(str(a)) │
>                              ╰─────────────────────────────────────────────────╯
>                              TypeError: expected str, bytes or os.PathLike      
>                              object, not NoneType 
> ```
> 
> I'm currently working on a fix, in the meantime, if someone has any idea or had similar situation let's talk!

Here I have opened an ofitial issue: https://github.com/immich-app/immich/issues/29537 and tomorrow I'll provide a PR with the related fix

**Comment by timglong** [comment]
Not sure if I'm missing something here, but I'm using an RTX 5050, which is Blackwell/sm_120 as far as I'm aware, and ML works with no issues besides a slow first search (see https://github.com/immich-app/immich/discussions/14547 for first-search stuff). I've used this GPU successfully with 2.5.6 through 2.7.5, all v3 RCs, 3.0.0, and 3.0.1, in both remote and local configs. I suppose I could just silently be using the CPU, but I have no errors in the logs and `nvidia-smi` shows models loading into memory, increased utilization during Smart Search jobs and searches, etc.

Edit: To make sure, I ran ML using the CPU only and again using CUDA. With the CPU, re-running the Smart Search job looked like it would take about 3 hours (painfully slow). With CUDA it completed in about 24 minutes.

**Comment by Tantrax007** [comment]
Hello @timglong, the problem I'm describing is specifically related to OCR, not general ML; facial recognition has been working correctly for me, but as I mentioned, OCR has not.

**Comment by Tantrax007** [comment]
Hello everyone again!

After following the steps outlined in this ticket: https://github.com/immich-app/immich/issues/29537, I've been able to fully utilize my RTX 5060. Therefore, at least in my experience, the error described here doesn't apply to my setup anymore.

**Comment by ekropotin** [comment]
**Closing this — the original diagnosis in the title was wrong, and I want to correct the record for anyone who lands here from search.**

**TL;DR:** The `release-cuda` image does **not** need a CUDA 12.8 base to work on Blackwell (sm_120). The `CUDA failure 35` this issue was filed about is a **driver / container GPU-passthrough problem on the host**, not a CUDA-version problem in the image. The base-image tag is a red herring.

**Why the base image doesn't matter:** onnxruntime ships **PTX**, and the NVIDIA driver JIT-compiles it to sm_120 at runtime (forward compatibility). So as long as the container can actually reach a recent-enough driver, it runs on Blackwell — regardless of the CUDA runtime baked into the image. The one-time cost of that JIT is the "slow first search" several people here have noticed; it's cached afterward. I verified this on a real RTX 5060 Ti — it runs on `CUDAExecutionProvider` even with image builds old enough to predate the RTX 50-series entirely.

**For those still hitting `CUDA failure 35` / `999`:** these are raised at driver init (`cuInit` / `cudaGetDeviceCount`) and mean the container can't talk to a working driver. Common causes, all host-side and image-independent:
- nvidia-container-toolkit / runtime not wired up (e.g. `--runtime=nvidia` failing to even start the container),
- host NVIDIA driver too old for Blackwell (needs a recent branch, r570+),
- driver libraries not correctly mounted into the container.

Fix the host GPU passthrough and the stock `release-cuda` works.

**Apologies for the confusion I created here** — both with the incorrect "needs CUDA 12.8" framing in the title and by pointing people to my community fork. The fork's CUDA-12.8 rebase turned out to be unnecessary; my own setup was really fixed by correcting driver passthrough. Please use the official image. Closing as resolved / not an image bug.

**Comment by insunaa** [comment]
For anyone using Podman:
`sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml`
to generate the cdi definitions and then
in the `hwaccel.ml.yaml`

```yaml
  cuda:
    devices:
      - nvidia.com/gpu=all
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities:
#                - gpu
```

**Comment by chirag350** [comment]
Was facing the same issue on my 3060 ti running immich in wsl, nvidia container toolkit **seemed** (did not test beyond listing torch devices and nvidia-smi) to work fine outside of immich however didn't work with immich_machine_learning, what fixed it was adding

```
devices:
      - /dev/dxg:/dev/dxg
```
to the compose file

do note that this is a fix only for people using wsl or docker desktop (which uses wsl)
